(function(a,d,v){function p(a){for(var b={},c,g,f=0;f<a.length;f++)g=a[f],c=g.r+g.s+g.m,g.c&&(b[c]||(b[c]=[]),b[c].push(a[f]));return b}function q(a){for(var b=1;b<arguments.length;b++){var c=arguments[b];try{if(c.isSupported)return c.send(a)}catch(g){}}}function m(){for(var a=0;a<B.length;a++)B[a]();F.length&&q(p(F.splice(0,F.length)),M,L,J);n=K=0}function t(r,b,c){c=c||{};0===c.bf&&e.isBF||(r={r:c.r||e.rid,s:c.s||a.ue_sid,m:c.m||a.ue_mid,mkt:c.mkt||a.ue_mkt,sn:c.sn||a.ue_sn,c:b,d:r,t:c.t||e.d(),
cs:c.c&&a.ue_qsl},c.b?q(p([r]),M,J):c.nb?q(p([r]),M,L,J):c.img||G[b]?q(p([r]),J):c.ff?(F.push(r),m()):c.n?(F.push(r),0===N?m():n||(n=d.setTimeout(m,N))):(F.push(r),K||(K=d.setTimeout(m,H))))}function z(a,b,c){I++;I==w&&t({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr");(I<w||c&&c.il)&&t(a,b,c)}function l(){if(!D){for(var a=0;a<b.length;a++)b[a]();for(a=0;a<B.length;a++)B[a]();q(p(F.splice(0,F.length)),M,J);D=!0}}var k={};(function(){function a(g){return 10>
g?"0"+g:g}function b(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(g){var a=A[g];return"string"===typeof a?a:"\\u"+("0000"+g.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(g,a){var r,A,u,k,n=f,l,E=a[g];E&&"object"===typeof E&&"function"===typeof E.toJSON&&(E=E.toJSON(g));"function"===typeof d&&(E=d.call(a,g,E));switch(typeof E){case "string":return b(E);case "number":return isFinite(E)?String(E):"null";case "boolean":case "null":return String(E);case "object":if(!E)return"null";
f+=e;l=[];if("[object Array]"===Object.prototype.toString.apply(E)){k=E.length;for(r=0;r<k;r+=1)l[r]=c(r,E)||"null";u=0===l.length?"[]":f?"[\n"+f+l.join(",\n"+f)+"\n"+n+"]":"["+l.join(",")+"]";f=n;return u}if(d&&"object"===typeof d)for(k=d.length,r=0;r<k;r+=1)"string"===typeof d[r]&&(A=d[r],(u=c(A,E))&&l.push(b(A)+(f?": ":":")+u));else for(A in E)Object.prototype.hasOwnProperty.call(E,A)&&(u=c(A,E))&&l.push(b(A)+(f?": ":":")+u);u=0===l.length?"{}":f?"{\n"+f+l.join(",\n"+f)+"\n"+n+"}":"{"+l.join(",")+
"}";f=n;return u}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(g){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(g){return this.valueOf()});var g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f,e,A={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},d;"function"!==typeof k.stringify&&(k.stringify=function(g,a,r){var A;e=f="";if("number"===typeof r)for(A=0;A<r;A+=1)e+=" ";else"string"===typeof r&&(e=r);if((d=a)&&"function"!==typeof a&&("object"!==typeof a||"number"!==typeof a.length))throw Error("JSON.stringify");return c("",{"":g})})})();var h=function(){function a(b,c){if(null==b)return c.push("!n");if("number"===typeof b)return c.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?c.push("'"+b.replace(/'/g,"\\'")+"u005C'"):c.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return c.push(b?"!t":"!f");if(b instanceof Array){c.push("*");for(var g=0;g<b.length;g++)a(b[g],c);return c.push(")")}if("object"==typeof b){c.push("(");for(g in b)b.hasOwnProperty(g)&&(c.push(g),a(b[g],c));return c.push(")")}return c.push("!n")}return{stringify:function(b){var c=[];a(b,c);return c.join("")}}}(),x=a.ue_qsl||2E3,w=1E3,y=function(){},u=d.JSON&&
d.JSON.stringify||k&&k.stringify,C=h.stringify,e=a.ue||{},h=a.uet||y;(a.uet||y)("bb","ue_frst_v2",{wb:1});var f="//"+a.ue_furl+"/1/batch/1/OE/",F=[],b=[],B=[],D=!1,n,K,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,H=void 0===a.ue_lpfi?1E4:a.ue_lpfi,G={"scheduled-delivery":1},I=0,L=function(){function r(){if(d.XDomainRequest){var g=new XDomainRequest;g.onerror=y;g.ontimeout=y;g.onprogress=y;g.onload=y;g.timeout=0;return g}if(d.XMLHttpRequest){g=new XMLHttpRequest;if(!("withCredentials"in g))throw"";return g}if(d.ActiveXObject){for(var a=
0;a<c.length&&!g;a++)try{g=new ActiveXObject(c[a]),c=[c[a]]}catch(r){}return g}}function b(g){for(var c=[],r=g[0]||{},A=0;A<g.length;A++){var f={};f[g[A].c]=g[A].d;c.push(f)}return{rid:r.r||e.rid,sid:r.s||a.ue_sid,mid:r.m||a.ue_mid,mkt:r.mkt||a.ue_mkt,sn:r.sn||a.ue_sn,reqs:c}}var c="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(g){for(var a in g)if(g.hasOwnProperty(a)&&g[a].length){var c=b(g[a]),A=r();
if(!A)throw"";A.open("POST",f,!0);A.setRequestHeader&&A.setRequestHeader("Content-type","text/plain");A.send(u(c))}},buildPOSTBodyLog:b,isSupported:!0}}(),J=function(){return{send:function(r){for(var b in r)if(r.hasOwnProperty(b)){for(var c=r[b],g=c,d={},R=void 0,A=0;A<g.length;A++)R=g[A].c,d[R]||(d[R]=[]),d[R].push(g[A]);var c=c[0]||{},g=c.sn||a.ue_sn,c=f+(c.m||a.ue_mid)+":"+(c.s||a.ue_sid)+":"+(c.r||e.rid)+(g?":"+g:""),g=[],R=c,A=[],k=void 0;for(k in d)if(d.hasOwnProperty(k))for(var P=0;P<d[k].length;P++){var n=
d[k][P],l=encodeURIComponent((n.cs?C:u)(n.d));A.push({l:l,t:n.t,p:1,c:k,d:n.cs?"c":"j"})}d=A;A=void 0;k="$";for(n=0;n<d.length;){P=d[n];A!=P.c?(R+=k+P.c+"=",k="&",A=P.c):R+=",";var l=R,h=P.d+":",m=P,R=(m.l.match(".{1,"+(x-R.length)+"}[^%]{0,2}")||[])[0]||"";m.l=m.l.substr(R.length);R=l+(h+R+":"+P.t);if(P.l)R+=":"+P.p++ +"_",g.push(R),R=c,k="$",A=0;else if(n++,1!=P.p)for(R+=":"+P.p+"_"+P.p,l=0;l<P.p-1;l++)g[g.length-l-1]+=P.p}g.push(R);c=g;for(g=0;g<c.length;g++)(new Image).src=c[g]}},isSupported:!0}}(),
M=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var c=L.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(f,u(c)))throw"";}},isSupported:!!navigator.sendBeacon}}();e._fic=J;e._fac=L;e._fbc=M;e._flq=F;e.sid=e.sid||a.ue_sid;e.mid=e.mid||a.ue_mid;e.furl=e.furl||a.ue_furl;e.sn=e.sn||a.ue_sn;e.isBF=function(){var a=d.performance||d.webkitPerformance,b=v.ue_backdetect&&v.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,c=e.bfini;return a&&a.navigation&&2===a.navigation.type||
1<c||!c&&1<b}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",y)}catch(Q){a.ueLogError(Q,{logLevel:"WARN"})}(function(){e.log&&e.log.isStub&&(e.log.replay(function(a,b,c){var g=a[2]||{};g.t=b;g.r=c;g.n=1;z(a[0],a[1],g)}),e.onunload.replay(function(a){b.push(a[0])}),e.onflush.replay(function(a){B.push(a[0])}))})();e.log=z;e.log.reset=function(){I=0};e.onunload=function(a){b.push(a)};e.onflush=function(a){B.push(a)};
e.attach("beforeunload",l);e.attach("pagehide",l);h("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,d){function v(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function p(f,d){if(!f)return{};f.m&&f.m.message&&(f=f.m);var b=d.m||d.message||"",b=f.m&&f.m.message?b+f.m.message:f.m&&f.m.target&&f.m.target.tagName?b+("Error handler invoked by "+f.m.target.tagName+" tag"):f.m?b+f.m:f.message?b+f.message:b+"Unknown error",b={m:b,f:f.f||f.sourceURL||f.fileName||f.filename||f.m&&f.m.target&&f.m.target.src,l:f.l||f.line||f.lineno||f.lineNumber,c:f.c?""+f.c:f.c,s:[],t:a.ue.d(),name:f.name,type:f.type,
csm:w+" "+(f.fromOnError?"onerror":"ueLogError")},k,h,n=0,m=0,t;k=f.stack||(f.err?f.err.stack:"");b.pageURL=d.pageURL||""+(window.location?window.location.href:"")||"missing";b.logLevel=d.logLevel||l;if(h=d.attribution)b.attribution=""+h;if(k&&k.split)for(b.csm+=" stack",h=k.split("\n");n<h.length&&b.s.length<y;)(k=h[n++])&&b.s.push(v(k));else for(b.csm+=" callee",h=q(f.args||arguments,"callee"),m=n=0;h&&n<y;)t=u,h.skipTrace||(k=h.toString())&&k.substr&&(t=0===m?4*u:t,t=1==m?2*u:t,b.s.push(k.substr(0,
t)),m++),h=q(h,"caller"),n++;if(!b.f&&0<b.s.length&&(n=b)&&n.s){var p;k=0<n.s.length?n.s[0]:"";h=1<n.s.length?n.s[1]:"";k&&(p=k.match(e));p&&3==p.length||!h||(p=h.match(C));p&&3==p.length&&(n.f=p[1],n.l=p[2])}return b}function q(a,e){try{return a[e]}catch(b){}}function m(f,e){if(f){var b=p(f,e);a.ue.log(b,e.channel||z,{nb:1});try{if(!f.fromOnError){var k=d.console,u=d.JSON,n="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(k){if(u&&u.stringify)try{n+=
u.stringify(b)}catch(l){n+="no info provided; converting to string failed"}else n+=b.m;"function"===typeof k.error?k.error(n,b):"function"===typeof k.log&&k.log(n,b)}}}catch(h){}}}function t(f,e){if(f&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ter.push(f);e=e||{};var b=f.logLevel||e.logLevel;e.logLevel=b;e.attribution=f.attribution||e.attribution;b&&b!==l&&b!==k&&b!==h&&b!==x||a.ue_err.ec++;b&&b!=l||ue_err.ecf++;m(f,e)}}if(!a.ueLogError||a.ueLogError.isStub){var z=a.ue_err_chan||"jserr",l="FATAL",k="ERROR",
h="WARN",x="DOWNGRADED",w="v5",y=20,u=256,C=/\(?([^\s]*):(\d+):\d+\)?/,e=/.*@(.*):(\d*)/;m.skipTrace=1;p.skipTrace=1;t.skipTrace=1;(function(){if(a.ue_err.erl){var f=a.ue_err.erl.length,e,b;for(e=0;e<f;e++)b=a.ue_err.erl[e],m(b.ex,b.info);ue_err.erl=[]}})();a.ueLogError=t}})(ue_csm,window);
(function(a,d){a.ue_cel||(a.ue_cel=function(){function v(a,d){d?d.r=w:d={r:w,c:1};d.clog&&k.clog?k.clog(a,d.ns||z,d):d.glog&&k.glog?k.glog(a,d.ns||z,d):k.log(a,d.ns||z,d)}function p(){var a=m.length;if(0<a){for(var d=[],e=0;e<a;e++){var f=m[e].api;f.ready()?(f.on({ts:k.d,ns:z}),t.push(m[e]),v({k:"mso",n:m[e].name,t:k.d()})):d.push(m[e])}m=d}}function q(){if(!q.executed){for(var a=0;a<t.length;a++)t[a].api.off&&t[a].api.off({ts:k.d,ns:z});v({k:"eod",t0:k.t0,t:k.d()},{c:1,il:1});q.executed=1;for(a=
0;a<t.length;a++)m.push(t[a]);t=[];clearTimeout(l)}}var m=[],t=[],z=a.ue_cel_ns||"cel",l,k=a.ue,h=a.uet,x=a.uex,w=k.rid,y=d.requestAnimationFrame||function(a){a()};if(k.isBF)v({k:"bft",t:k.d()});else return"function"==typeof h&&h("bb","csmCELLSframework",{wb:1}),setTimeout(p,0),k.onunload(q),l=setTimeout(q,6E5),"function"==typeof x&&x("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,d){m.push({name:a,api:d});v({k:"mrg",n:a,t:k.d()});p()},reset:function(a){v({k:"rst",t0:k.t0,t:k.d()});m=
m.concat(t);t=[];for(var d=m.length,e=0;e<d;e++)m[e].api.off(),m[e].api.reset();w=a||k.rid;p();clearTimeout(l);l=setTimeout(q,6E5);q.executed=0},timeout:function(a,k){return d.setTimeout(function(){y(a)},k)},log:v}}())})(ue_csm,window);
(function(a,d,v){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function p(){var e={w:t.width,aw:t.availWidth,h:t.height,ah:t.availHeight,cd:t.colorDepth,pd:t.pixelDepth},f={w:(v.body||{}).scrollWidth,h:(v.body||{}).scrollHeight};h&&h.w==e.w&&h.h==e.h&&h.aw==e.aw&&h.ah==e.ah&&h.pd==e.pd&&h.cd==e.cd||(h=e,h.t=l(),h.k="sci",y(h));x&&x.w==f.w&&x.h==f.h||(x=f,x.t=l(),x.k="doi",y(x));z=a.ue_cel.timeout(p,k)}function q(){y({k:"ebl",t:l()},{ff:1})}function m(){y({k:"efo",t:l()})}var t,z,l,k,h,x,w=a.ue,y=a.ue_cel.log,
u=a.uet,C=a.uex;"function"==typeof u&&u("bb","csmCELLSpdm",{wb:1});return{on:function(e){k=e.timespan||500;l=e.ts;t=d.screen;w.attach&&(w.attach("blur",q,d),w.attach("focus",m,d));e=d.location;y({k:"pmd",o:e.origin,p:e.pathname,t:l()});a.ue_cel.timeout(p,0);"function"==typeof C&&C("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(z);w.detach&&(w.detach("blur",q,d),w.detach("focus",m,d));w.count&&(w.count("cel.PDM.TotalExecutions",0),w.count("cel.PDM.TotalExecutionTime",0),w.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return v.body&&a.ue_cel&&a.ue_cel.log},reset:function(){h=x=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,d){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function v(){var a=z(),f={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};q&&q.w==f.w&&q.h==f.h&&q.x==f.x&&q.y==f.y||(f.t=a,f.k="vpi",q=f,x(q,{clog:1}));m=0;l=z()-a;k+=1}function p(){m||(m=a.ue_cel.timeout(v,t))}var q,m,t,z,l=0,k=0,h=a.ue,x=a.ue_cel.log,w=a.uet,y=a.uex,u=h.attach,C=h.detach;"function"==typeof w&&w("bb","csmCELLSvpm",{wb:1});return{on:function(e){z=e.ts;t=e.timespan||100;a.ue_cel.timeout(v,0);u&&(u("scroll",p),
u("resize",p));"function"==typeof y&&y("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(m);C&&(C("scroll",p),C("resize",p));h.count&&(h.count("cel.VPI.TotalExecutions",k),h.count("cel.VPI.TotalExecutionTime",l),h.count("cel.VPI.AverageExecutionTime",l/k))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=void 0},getVpi:function(){return q}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,d,v){var p=a.ue||{};!p.isBF&&!a.ue_fem&&v.querySelector&&d.getComputedStyle&&[].forEach&&(a.ue_fem=a.ue_bwd?function(){function q(a,g){return a>g?3>a-g:3>g-a}function m(a,g,c){var r;a:{try{if(a){var b=a.getBoundingClientRect();r={x:b.left+c.x|0,y:b.top+c.y|0,w:b.width|0,h:b.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else r=void 0;break a}catch(f){}r=void 0}if(r&&!a.cel_b)a.cel_b=r,F({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:g,k:"ewi",cl:a.className},
{clog:1});else{if(c=r)c=a.cel_b,b=r,c=b.d===c.d&&1===b.d?!1:!(q(c.x,b.x)&&q(c.y,b.y)&&q(c.w,b.w)&&q(c.h,b.h)&&c.d===b.d);c&&(a.cel_b=r,F({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:g,k:"ewi"},{clog:1}))}}function t(a,g,r){var b;b=a.c?v.getElementsByClassName(a.c):a.id?[v.getElementById(a.id)]:v.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<b.length;widgetIndex++){var e=b[widgetIndex];e&&(e.cel_n||(e.cel_n=e.getAttribute("cel_widget_id")||(a.id_gen||f)(e,widgetIndex)||
e.id),a.w.push(e),k(c,e,g,r))}}function z(a,g){b.contains(a)||F({n:a.cel_n,t:g,k:"ewd"},{clog:1})}function l(a){J.length&&ue_cel.timeout(function(){for(var c=R(),r=!1;R()-c<u&&!r;){for(r=Q;0<r--&&0<J.length;){var b=J.shift();g[b.type](b.elem,b.time,b.pageOffset)}r=0===J.length}M++;l(a)},0)}function k(a,g,c,r){J.push({type:a,elem:g,time:c,pageOffset:r})}function h(a,g,c){for(var r=0;r<e.length;r++)for(var b=e[r].w||[],f=0;f<b.length;f++)k(a,b[f],g,c)}function x(){L||(L=a.ue_cel.timeout(function(){L=
null;var a={x:d.pageXOffset,y:d.pageYOffset},g=C();h(r,g);for(var c=0;c<e.length;c++)k(O,e[c],g,a);l(g)},y))}function w(){L||I||(I=a.ue_cel.timeout(function(){I=null;var a={x:d.pageXOffset,y:d.pageYOffset},g=C();h(c,g,a);l(g)},y))}var y=50,u=4.5,C,e=[],f=function(){},F=a.ue_cel.log,b,B,D,n,K=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!K,H,G,I,L,J=[],M=0,Q=null,r="removedWidget",O="updateWidgets",c="processWidget",g,S=d.performance||{},R=S.now&&function(){return S.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(c){function r(){if(D&&n&&b&&b.contains&&b.getBoundingClientRect&&C){g={removedWidget:z,updateWidgets:t,processWidget:m};if(N){var a={attributes:!0,subtree:!0};H=new K(w);G=new K(x);H.observe(b,a);G.observe(b,{childList:!0,subtree:!0});G.observe(B,a)}else D.call(b,"DOMAttrModified",w),D.call(b,"DOMNodeInserted",x),D.call(b,"DOMNodeRemoved",x),D.call(B,"DOMNodeInserted",w),D.call(B,"DOMNodeRemoved",
w);x()}}b=v.body;B=v.head;D=b.addEventListener;n=b.removeEventListener;C=c.ts;e=a.cel_widgets||[];Q=c.bs||5;p.deffered?r():p.attach&&p.attach("load",r);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){D&&n&&b&&b.contains&&b.getBoundingClientRect&&C&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),n.call(b,"DOMAttrModified",w),n.call(b,"DOMNodeInserted",x),n.call(b,"DOMNodeRemoved",x),n.call(B,"DOMNodeInserted",w),n.call(B,"DOMNodeRemoved",w));p.count&&p.count("cel.widgets.batchesProcessed",
M)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){e=a.cel_widgets||[]}}}():function(){function q(){a.ue_cel.timeout(function(){f.splice(0).forEach(function(a){F(a,{clog:1})})},0)}function m(a){for(var b={x:d.pageXOffset,y:d.pageYOffset},r=0;r<C.length;r++){var e=C[r];if(e.w&&e.w.length)for(var c=0;c<e.w.length;c++){var g=e.w[c],S;a:{try{var k=g,A=b;if(k){var u=k.getBoundingClientRect();S={x:u.left+A.x|0,y:u.top+A.y|0,w:u.width|0,h:u.height|0,d:(0===k.offsetWidth&&0===k.offsetHeight)|
0}}else S=void 0;break a}catch(P){}S=void 0}if(S&&!g.cel_b)g.cel_b=S,f.push({n:g.cel_n,w:g.cel_b.w,h:g.cel_b.h,d:g.cel_b.d,x:g.cel_b.x,y:g.cel_b.y,t:a,k:"ewi",cl:g.className});else{if(k=S)k=g.cel_b,A=S,k=A.d===k.d&&1===A.d?!1:!(z(k.x,A.x)&&z(k.y,A.y)&&z(k.w,A.w)&&z(k.h,A.h)&&k.d===A.d);k&&(g.cel_b=S,f.push({n:g.cel_n,w:g.cel_b.w,h:g.cel_b.h,d:g.cel_b.d,x:g.cel_b.x,y:g.cel_b.y,t:a,k:"ewi"}))}}}}function t(a){for(var d=0;d<C.length;d++){var r=C[d],O;O=r;O=O.c?v.getElementsByClassName(O.c):O.id?[v.getElementById(O.id)]:
v.querySelectorAll(O.s);var c=r.w||[],g;for(g=0;g<c.length;g++){var S=c[g];b.contains(S)||f.push({n:S.cel_n,t:a,k:"ewd"})}r.w=[];for(g=0;g<O.length;g++)if(c=O[g])c.cel_n||(c.cel_n=c.getAttribute("cel_widget_id")||(r.id_gen||e)(c,g)||c.id),r.w.push(c)}k()}function z(a,b){return a>b?3>a-b:3>b-a}function l(){L||(L=a.ue_cel.timeout(function(){L=null;h("dwe",t);q()},x))}function k(){L||I||(I=a.ue_cel.timeout(function(){I=null;h("dwpc",m);q()},x))}function h(a,b){var r=u();b(r);var e=u(),r=e-r;r<=w?e=0:
e-J>=y?(J=e,e=0):(ue_fem.off(),e=1);(f.length||e)&&f.push({k:"ewt",e:a,d:r,ex:e,t:u()})}var x=50,w=10,y=3E3,u,C=[],e=function(){},f=[],F=a.ue_cel.log,b,B,D,n,K=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!K,H,G,I,L,J=-y;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(f){function e(){if(D&&n&&b&&b.contains&&b.getBoundingClientRect&&u){if(N){var a={attributes:!0,subtree:!0};H=new K(k);G=new K(l);H.observe(b,a);G.observe(b,{childList:!0,subtree:!0});
G.observe(B,a)}else D.call(b,"DOMAttrModified",k),D.call(b,"DOMNodeInserted",l),D.call(b,"DOMNodeRemoved",l),D.call(B,"DOMNodeInserted",k),D.call(B,"DOMNodeRemoved",k);l()}}b=v.body;B=v.head;D=b.addEventListener;n=b.removeEventListener;u=f.ts;C=a.cel_widgets||[];p.deffered?e():p.attach&&p.attach("load",e);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){D&&n&&b&&b.contains&&b.getBoundingClientRect&&u&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),n.call(b,"DOMAttrModified",
k),n.call(b,"DOMNodeInserted",l),n.call(b,"DOMNodeRemoved",l),n.call(B,"DOMNodeInserted",k),n.call(B,"DOMNodeRemoved",k))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){C=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);