(function(a,c,v){function r(a){for(var b={},f,g,d=0;d<a.length;d++)g=a[d],f=g.r+g.s+g.m,g.c&&(b[f]||(b[f]=[]),b[f].push(a[d]));return b}function q(a){for(var b=1;b<arguments.length;b++){var f=arguments[b];try{if(f.isSupported)return f.send(a)}catch(g){}}}function m(){for(var a=0;a<l.length;a++)l[a]();E.length&&q(r(E.splice(0,E.length)),M,L,J);C=K=0}function p(t,b,f){f=f||{};0===f.bf&&e.isBF||(t={r:f.r||e.rid,s:f.s||a.ue_sid,m:f.m||a.ue_mid,mkt:f.mkt||a.ue_mkt,sn:f.sn||a.ue_sn,c:b,d:t,t:f.t||e.d(),
cs:f.c&&a.ue_qsl},f.b?q(r([t]),M,J):f.nb?q(r([t]),M,L,J):f.img||G[b]?q(r([t]),J):f.ff?(E.push(t),m()):f.n?(E.push(t),0===N?m():C||(C=c.setTimeout(m,N))):(E.push(t),K||(K=c.setTimeout(m,H))))}function w(a,b,f){I++;I==x&&p({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},c.ue_err_chan||"jserr");(I<x||f&&f.il)&&p(a,b,f)}function n(){if(!D){for(var a=0;a<d.length;a++)d[a]();for(a=0;a<l.length;a++)l[a]();q(r(E.splice(0,E.length)),M,J);D=!0}}var h={};(function(){function a(g){return 10>
g?"0"+g:g}function b(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(g){var a=A[g];return"string"===typeof a?a:"\\u"+("0000"+g.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function f(g,a){var t,A,c,u,h=d,n,F=a[g];F&&"object"===typeof F&&"function"===typeof F.toJSON&&(F=F.toJSON(g));"function"===typeof l&&(F=l.call(a,g,F));switch(typeof F){case "string":return b(F);case "number":return isFinite(F)?String(F):"null";case "boolean":case "null":return String(F);case "object":if(!F)return"null";
d+=e;n=[];if("[object Array]"===Object.prototype.toString.apply(F)){u=F.length;for(t=0;t<u;t+=1)n[t]=f(t,F)||"null";c=0===n.length?"[]":d?"[\n"+d+n.join(",\n"+d)+"\n"+h+"]":"["+n.join(",")+"]";d=h;return c}if(l&&"object"===typeof l)for(u=l.length,t=0;t<u;t+=1)"string"===typeof l[t]&&(A=l[t],(c=f(A,F))&&n.push(b(A)+(d?": ":":")+c));else for(A in F)Object.prototype.hasOwnProperty.call(F,A)&&(c=f(A,F))&&n.push(b(A)+(d?": ":":")+c);c=0===n.length?"{}":d?"{\n"+d+n.join(",\n"+d)+"\n"+h+"}":"{"+n.join(",")+
"}";d=h;return c}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(g){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(g){return this.valueOf()});var g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
d,e,A={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;"function"!==typeof h.stringify&&(h.stringify=function(g,a,t){var A;e=d="";if("number"===typeof t)for(A=0;A<t;A+=1)e+=" ";else"string"===typeof t&&(e=t);if((l=a)&&"function"!==typeof a&&("object"!==typeof a||"number"!==typeof a.length))throw Error("JSON.stringify");return f("",{"":g})})})();var k=function(){function a(b,f){if(null==b)return f.push("!n");if("number"===typeof b)return f.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?f.push("'"+b.replace(/'/g,"\\'")+"u005C'"):f.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return f.push(b?"!t":"!f");if(b instanceof Array){f.push("*");for(var g=0;g<b.length;g++)a(b[g],f);return f.push(")")}if("object"==typeof b){f.push("(");for(g in b)b.hasOwnProperty(g)&&(f.push(g),a(b[g],f));return f.push(")")}return f.push("!n")}return{stringify:function(b){var f=[];a(b,f);return f.join("")}}}(),y=a.ue_qsl||2E3,x=1E3,z=function(){},u=c.JSON&&
c.JSON.stringify||h&&h.stringify,B=k.stringify,e=a.ue||{},k=a.uet||z;(a.uet||z)("bb","ue_frst_v2",{wb:1});var b="//"+a.ue_furl+"/1/batch/1/OE/",E=[],d=[],l=[],D=!1,C,K,N=void 0===a.ue_hpfi?1E3:a.ue_hpfi,H=void 0===a.ue_lpfi?1E4:a.ue_lpfi,G={"scheduled-delivery":1},I=0,L=function(){function t(){if(c.XDomainRequest){var g=new XDomainRequest;g.onerror=z;g.ontimeout=z;g.onprogress=z;g.onload=z;g.timeout=0;return g}if(c.XMLHttpRequest){g=new XMLHttpRequest;if(!("withCredentials"in g))throw"";return g}if(c.ActiveXObject){for(var a=
0;a<f.length&&!g;a++)try{g=new ActiveXObject(f[a]),f=[f[a]]}catch(t){}return g}}function d(g){for(var f=[],t=g[0]||{},A=0;A<g.length;A++){var b={};b[g[A].c]=g[A].d;f.push(b)}return{rid:t.r||e.rid,sid:t.s||a.ue_sid,mid:t.m||a.ue_mid,mkt:t.mkt||a.ue_mkt,sn:t.sn||a.ue_sn,reqs:f}}var f="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(g){for(var a in g)if(g.hasOwnProperty(a)&&g[a].length){var f=d(g[a]),A=t();
if(!A)throw"";A.open("POST",b,!0);A.setRequestHeader&&A.setRequestHeader("Content-type","text/plain");A.send(u(f))}},buildPOSTBodyLog:d,isSupported:!0}}(),J=function(){return{send:function(t){for(var d in t)if(t.hasOwnProperty(d)){for(var f=t[d],g=f,l={},c=void 0,A=0;A<g.length;A++)c=g[A].c,l[c]||(l[c]=[]),l[c].push(g[A]);var f=f[0]||{},g=f.sn||a.ue_sn,f=b+(f.m||a.ue_mid)+":"+(f.s||a.ue_sid)+":"+(f.r||e.rid)+(g?":"+g:""),g=[],c=f,A=[],h=void 0;for(h in l)if(l.hasOwnProperty(h))for(var P=0;P<l[h].length;P++){var n=
l[h][P],k=encodeURIComponent((n.cs?B:u)(n.d));A.push({l:k,t:n.t,p:1,c:h,d:n.cs?"c":"j"})}l=A;A=void 0;h="$";for(n=0;n<l.length;){P=l[n];A!=P.c?(c+=h+P.c+"=",h="&",A=P.c):c+=",";var k=c,m=P.d+":",E=P,c=(E.l.match(".{1,"+(y-c.length)+"}[^%]{0,2}")||[])[0]||"";E.l=E.l.substr(c.length);c=k+(m+c+":"+P.t);if(P.l)c+=":"+P.p++ +"_",g.push(c),c=f,h="$",A=0;else if(n++,1!=P.p)for(c+=":"+P.p+"_"+P.p,k=0;k<P.p-1;k++)g[g.length-k-1]+=P.p}g.push(c);f=g;for(g=0;g<f.length;g++)(new Image).src=f[g]}},isSupported:!0}}(),
M=function(){return{send:function(a){for(var d in a)if(a.hasOwnProperty(d)){var f=L.buildPOSTBodyLog(a[d]);if(!navigator.sendBeacon(b,u(f)))throw"";}},isSupported:!!navigator.sendBeacon}}();e._fic=J;e._fac=L;e._fbc=M;e._flq=E;e.sid=e.sid||a.ue_sid;e.mid=e.mid||a.ue_mid;e.furl=e.furl||a.ue_furl;e.sn=e.sn||a.ue_sn;e.isBF=function(){var a=c.performance||c.webkitPerformance,b=v.ue_backdetect&&v.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,f=e.bfini;return a&&a.navigation&&2===a.navigation.type||
1<f||!f&&1<b}();try{c.amznJQ&&c.amznJQ.declareAvailable&&c.amznJQ.declareAvailable("forester-client"),c.P&&c.P.register&&c.P.register("forester-client",z)}catch(Q){a.ueLogError(Q,{logLevel:"WARN"})}(function(){e.log&&e.log.isStub&&(e.log.replay(function(a,b,f){var g=a[2]||{};g.t=b;g.r=f;g.n=1;w(a[0],a[1],g)}),e.onunload.replay(function(a){d.push(a[0])}),e.onflush.replay(function(a){l.push(a[0])}))})();e.log=w;e.log.reset=function(){I=0};e.onunload=function(a){d.push(a)};e.onflush=function(a){l.push(a)};
e.attach("beforeunload",n);e.attach("pagehide",n);k("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,c){function v(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function r(b,c){if(!b)return{};var d="INFO"===c.logLevel;b.m&&b.m.message&&(b=b.m);var l=c.m||c.message||"",l=b.m&&b.m.message?l+b.m.message:b.m&&b.m.target&&b.m.target.tagName?l+("Error handler invoked by "+b.m.target.tagName+" tag"):b.m?l+b.m:b.message?l+b.message:l+"Unknown error",l={m:l,name:b.name,type:b.type,csm:x+" "+(b.fromOnError?"onerror":"ueLogError")},h,k,m=0,p;l.logLevel=c.logLevel||n;if(h=c.attribution)l.attribution=
""+h;if(!d){l.pageURL=c.pageURL||""+(window.location?window.location.href:"")||"missing";l.f=b.f||b.sourceURL||b.fileName||b.filename||b.m&&b.m.target&&b.m.target.src;l.l=b.l||b.line||b.lineno||b.lineNumber;l.c=b.c?""+b.c:b.c;l.s=[];l.t=a.ue.d();if((d=b.stack||(b.err?b.err.stack:""))&&d.split)for(l.csm+=" stack",h=d.split("\n");m<h.length&&l.s.length<z;)(d=h[m++])&&l.s.push(v(d));else for(l.csm+=" callee",k=q(b.args||arguments,"callee"),h=m=0;k&&m<z;)p=u,k.skipTrace||(d=k.toString())&&d.substr&&(p=
0===h?4*u:p,p=1==h?2*u:p,l.s.push(d.substr(0,p)),h++),k=q(k,"caller"),m++;if(!l.f&&0<l.s.length&&(m=l)&&m.s){var r,d=0<m.s.length?m.s[0]:"";h=1<m.s.length?m.s[1]:"";d&&(r=d.match(e));r&&3==r.length||!h||(r=h.match(B));r&&3==r.length&&(m.f=r[1],m.l=r[2])}}return l}function q(a,e){try{return a[e]}catch(d){}}function m(b,e){if(b){var d=r(b,e);a.ue.log(d,e.channel||w,{nb:1});"function"===typeof ue_err.eh&&ue_err.eh(b,e);try{if(!b.fromOnError){var l=c.console,h=c.JSON,u="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";
if(l){if(h&&h.stringify)try{u+=h.stringify(d)}catch(n){u+="no info provided; converting to string failed"}else u+=d.m;"function"===typeof l.error?l.error(u,d):"function"===typeof l.log&&l.log(u,d)}}}catch(k){}}}function p(b,e){if(b&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ter.push(b);e=e||{};var d=b.logLevel||e.logLevel;e.logLevel=d;e.attribution=b.attribution||e.attribution;d&&d!==n&&d!==h&&d!==k&&d!==y||a.ue_err.ec++;d&&d!=n||ue_err.ecf++;m(b,e)}}if(!a.ueLogError||a.ueLogError.isStub){var w=a.ue_err_chan||
"jserr",n="FATAL",h="ERROR",k="WARN",y="DOWNGRADED",x="v5",z=20,u=256,B=/\(?([^\s]*):(\d+):\d+\)?/,e=/.*@(.*):(\d*)/;m.skipTrace=1;r.skipTrace=1;p.skipTrace=1;(function(){if(a.ue_err.erl){var b=a.ue_err.erl.length,e,d;for(e=0;e<b;e++)d=a.ue_err.erl[e],m(d.ex,d.info);ue_err.erl=[]}})();a.ueLogError=p}})(ue_csm,window);
(function(a,c){a.ue_cel||(a.ue_cel=function(){function v(a,c){c?c.r=x:c={r:x,c:1};c.clog&&h.clog?h.clog(a,c.ns||w,c):c.glog&&h.glog?h.glog(a,c.ns||w,c):h.log(a,c.ns||w,c)}function r(){var a=m.length;if(0<a){for(var c=[],e=0;e<a;e++){var b=m[e].api;b.ready()?(b.on({ts:h.d,ns:w}),p.push(m[e]),v({k:"mso",n:m[e].name,t:h.d()})):c.push(m[e])}m=c}}function q(){if(!q.executed){for(var a=0;a<p.length;a++)p[a].api.off&&p[a].api.off({ts:h.d,ns:w});v({k:"eod",t0:h.t0,t:h.d()},{c:1,il:1});q.executed=1;for(a=
0;a<p.length;a++)m.push(p[a]);p=[];clearTimeout(n)}}var m=[],p=[],w=a.ue_cel_ns||"cel",n,h=a.ue,k=a.uet,y=a.uex,x=h.rid,z=c.requestAnimationFrame||function(a){a()};if(h.isBF)v({k:"bft",t:h.d()});else return"function"==typeof k&&k("bb","csmCELLSframework",{wb:1}),setTimeout(r,0),h.onunload(q),n=setTimeout(q,6E5),"function"==typeof y&&y("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,c){m.push({name:a,api:c});v({k:"mrg",n:a,t:h.d()});r()},reset:function(a){v({k:"rst",t0:h.t0,t:h.d()});m=
m.concat(p);p=[];for(var c=m.length,e=0;e<c;e++)m[e].api.off(),m[e].api.reset();x=a||h.rid;r();clearTimeout(n);n=setTimeout(q,6E5);q.executed=0},timeout:function(a,h){return c.setTimeout(function(){z(a)},h)},log:v}}())})(ue_csm,window);
(function(a,c,v){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function r(){var e={w:p.width,aw:p.availWidth,h:p.height,ah:p.availHeight,cd:p.colorDepth,pd:p.pixelDepth},b={w:(v.body||{}).scrollWidth,h:(v.body||{}).scrollHeight};k&&k.w==e.w&&k.h==e.h&&k.aw==e.aw&&k.ah==e.ah&&k.pd==e.pd&&k.cd==e.cd||(k=e,k.t=n(),k.k="sci",z(k));y&&y.w==b.w&&y.h==b.h||(y=b,y.t=n(),y.k="doi",z(y));w=a.ue_cel.timeout(r,h)}function q(){z({k:"ebl",t:n()},{ff:1})}function m(){z({k:"efo",t:n()})}var p,w,n,h,k,y,x=a.ue,z=a.ue_cel.log,
u=a.uet,B=a.uex;"function"==typeof u&&u("bb","csmCELLSpdm",{wb:1});return{on:function(e){h=e.timespan||500;n=e.ts;p=c.screen;x.attach&&(x.attach("blur",q,c),x.attach("focus",m,c));e=c.location;z({k:"pmd",o:e.origin,p:e.pathname,t:n()});a.ue_cel.timeout(r,0);"function"==typeof B&&B("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(w);x.detach&&(x.detach("blur",q,c),x.detach("focus",m,c));x.count&&(x.count("cel.PDM.TotalExecutions",0),x.count("cel.PDM.TotalExecutionTime",0),x.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return v.body&&a.ue_cel&&a.ue_cel.log},reset:function(){k=y=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,c){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function v(){var a=w(),b={w:c.innerWidth,h:c.innerHeight,x:c.pageXOffset,y:c.pageYOffset};q&&q.w==b.w&&q.h==b.h&&q.x==b.x&&q.y==b.y||(b.t=a,b.k="vpi",q=b,y(q,{clog:1}));m=0;n=w()-a;h+=1}function r(){m||(m=a.ue_cel.timeout(v,p))}var q,m,p,w,n=0,h=0,k=a.ue,y=a.ue_cel.log,x=a.uet,z=a.uex,u=k.attach,B=k.detach;"function"==typeof x&&x("bb","csmCELLSvpm",{wb:1});return{on:function(e){w=e.ts;p=e.timespan||100;a.ue_cel.timeout(v,0);u&&(u("scroll",r),
u("resize",r));"function"==typeof z&&z("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(m);B&&(B("scroll",r),B("resize",r));k.count&&(k.count("cel.VPI.TotalExecutions",h),k.count("cel.VPI.TotalExecutionTime",n),k.count("cel.VPI.AverageExecutionTime",n/h))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){q=void 0},getVpi:function(){return q}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,c,v){var r=a.ue||{};!r.isBF&&!a.ue_fem&&v.querySelector&&c.getComputedStyle&&[].forEach&&(a.ue_fem=a.ue_bwd?function(){function q(a,g){return a>g?3>a-g:3>g-a}function m(a,g,f){var t;a:{try{if(a){var b=a.getBoundingClientRect();t={x:b.left+f.x|0,y:b.top+f.y|0,w:b.width|0,h:b.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else t=void 0;break a}catch(d){}t=void 0}if(t&&!a.cel_b)a.cel_b=t,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:g,k:"ewi",cl:a.className},
{clog:1});else{if(f=t)f=a.cel_b,b=t,f=b.d===f.d&&1===b.d?!1:!(q(f.x,b.x)&&q(f.y,b.y)&&q(f.w,b.w)&&q(f.h,b.h)&&f.d===b.d);f&&(a.cel_b=t,E({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:g,k:"ewi"},{clog:1}))}}function p(a,g,t){var d;d=a.c?v.getElementsByClassName(a.c):a.id?[v.getElementById(a.id)]:v.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<d.length;widgetIndex++){var e=d[widgetIndex];e&&(e.cel_n||(e.cel_n=e.getAttribute("cel_widget_id")||(a.id_gen||b)(e,widgetIndex)||
e.id),a.w.push(e),h(f,e,g,t))}}function w(a,g){d.contains(a)||E({n:a.cel_n,t:g,k:"ewd"},{clog:1})}function n(a){J.length&&ue_cel.timeout(function(){for(var f=S(),t=!1;S()-f<u&&!t;){for(t=Q;0<t--&&0<J.length;){var b=J.shift();g[b.type](b.elem,b.time,b.pageOffset)}t=0===J.length}M++;n(a)},0)}function h(a,g,f,t){J.push({type:a,elem:g,time:f,pageOffset:t})}function k(a,g,f){for(var t=0;t<e.length;t++)for(var b=e[t].w||[],d=0;d<b.length;d++)h(a,b[d],g,f)}function y(){L||(L=a.ue_cel.timeout(function(){L=
null;var a={x:c.pageXOffset,y:c.pageYOffset},g=B();k(t,g);for(var f=0;f<e.length;f++)h(O,e[f],g,a);n(g)},z))}function x(){L||I||(I=a.ue_cel.timeout(function(){I=null;var a={x:c.pageXOffset,y:c.pageYOffset},g=B();k(f,g,a);n(g)},z))}var z=50,u=4.5,B,e=[],b=function(){},E=a.ue_cel.log,d,l,D,C,K=c.MutationObserver||c.WebKitMutationObserver||c.MozMutationObserver,N=!!K,H,G,I,L,J=[],M=0,Q=null,t="removedWidget",O="updateWidgets",f="processWidget",g,R=c.performance||{},S=R.now&&function(){return R.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(f){function t(){if(D&&C&&d&&d.contains&&d.getBoundingClientRect&&B){g={removedWidget:w,updateWidgets:p,processWidget:m};if(N){var a={attributes:!0,subtree:!0};H=new K(x);G=new K(y);H.observe(d,a);G.observe(d,{childList:!0,subtree:!0});G.observe(l,a)}else D.call(d,"DOMAttrModified",x),D.call(d,"DOMNodeInserted",y),D.call(d,"DOMNodeRemoved",y),D.call(l,"DOMNodeInserted",x),D.call(l,"DOMNodeRemoved",
x);y()}}d=v.body;l=v.head;D=d.addEventListener;C=d.removeEventListener;B=f.ts;e=a.cel_widgets||[];Q=f.bs||5;r.deffered?t():r.attach&&r.attach("load",t);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){D&&C&&d&&d.contains&&d.getBoundingClientRect&&B&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),C.call(d,"DOMAttrModified",x),C.call(d,"DOMNodeInserted",y),C.call(d,"DOMNodeRemoved",y),C.call(l,"DOMNodeInserted",x),C.call(l,"DOMNodeRemoved",x));r.count&&r.count("cel.widgets.batchesProcessed",
M)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){e=a.cel_widgets||[]}}}():function(){function q(){a.ue_cel.timeout(function(){b.splice(0).forEach(function(a){E(a,{clog:1})})},0)}function m(a){for(var d={x:c.pageXOffset,y:c.pageYOffset},t=0;t<B.length;t++){var e=B[t];if(e.w&&e.w.length)for(var f=0;f<e.w.length;f++){var g=e.w[f],l;a:{try{var h=g,A=d;if(h){var u=h.getBoundingClientRect();l={x:u.left+A.x|0,y:u.top+A.y|0,w:u.width|0,h:u.height|0,d:(0===h.offsetWidth&&0===h.offsetHeight)|
0}}else l=void 0;break a}catch(P){}l=void 0}if(l&&!g.cel_b)g.cel_b=l,b.push({n:g.cel_n,w:g.cel_b.w,h:g.cel_b.h,d:g.cel_b.d,x:g.cel_b.x,y:g.cel_b.y,t:a,k:"ewi",cl:g.className});else{if(h=l)h=g.cel_b,A=l,h=A.d===h.d&&1===A.d?!1:!(w(h.x,A.x)&&w(h.y,A.y)&&w(h.w,A.w)&&w(h.h,A.h)&&h.d===A.d);h&&(g.cel_b=l,b.push({n:g.cel_n,w:g.cel_b.w,h:g.cel_b.h,d:g.cel_b.d,x:g.cel_b.x,y:g.cel_b.y,t:a,k:"ewi"}))}}}}function p(a){for(var l=0;l<B.length;l++){var t=B[l],O;O=t;O=O.c?v.getElementsByClassName(O.c):O.id?[v.getElementById(O.id)]:
v.querySelectorAll(O.s);var f=t.w||[],g;for(g=0;g<f.length;g++){var c=f[g];d.contains(c)||b.push({n:c.cel_n,t:a,k:"ewd"})}t.w=[];for(g=0;g<O.length;g++)if(f=O[g])f.cel_n||(f.cel_n=f.getAttribute("cel_widget_id")||(t.id_gen||e)(f,g)||f.id),t.w.push(f)}h()}function w(a,b){return a>b?3>a-b:3>b-a}function n(){L||(L=a.ue_cel.timeout(function(){L=null;k("dwe",p);q()},y))}function h(){L||I||(I=a.ue_cel.timeout(function(){I=null;k("dwpc",m);q()},y))}function k(a,d){var t=u();d(t);var e=u(),t=e-t;t<=x?e=0:
e-J>=z?(J=e,e=0):(ue_fem.off(),e=1);(b.length||e)&&b.push({k:"ewt",e:a,d:t,ex:e,t:u()})}var y=50,x=10,z=3E3,u,B=[],e=function(){},b=[],E=a.ue_cel.log,d,l,D,C,K=c.MutationObserver||c.WebKitMutationObserver||c.MozMutationObserver,N=!!K,H,G,I,L,J=-z;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(b){function e(){if(D&&C&&d&&d.contains&&d.getBoundingClientRect&&u){if(N){var a={attributes:!0,subtree:!0};H=new K(h);G=new K(n);H.observe(d,a);G.observe(d,{childList:!0,subtree:!0});
G.observe(l,a)}else D.call(d,"DOMAttrModified",h),D.call(d,"DOMNodeInserted",n),D.call(d,"DOMNodeRemoved",n),D.call(l,"DOMNodeInserted",h),D.call(l,"DOMNodeRemoved",h);n()}}d=v.body;l=v.head;D=d.addEventListener;C=d.removeEventListener;u=b.ts;B=a.cel_widgets||[];r.deffered?e():r.attach&&r.attach("load",e);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){D&&C&&d&&d.contains&&d.getBoundingClientRect&&u&&(G&&(G.disconnect(),G=null),H&&(H.disconnect(),H=null),C.call(d,"DOMAttrModified",
h),C.call(d,"DOMNodeInserted",n),C.call(d,"DOMNodeRemoved",n),C.call(l,"DOMNodeInserted",h),C.call(l,"DOMNodeRemoved",h))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){B=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);