(function(){if(typeof window.SCUI==="undefined"){window.SCUI={};
}SCUI.SpooferMenu=function($){this.$=($||window.jQuery||window.$);
this.started=false;
this.init();
};
var spoofProto=SCUI.SpooferMenu.prototype;
spoofProto.init=function(){if(!this.started){this.$("#spooferSpacerDiv").prependTo("body");
this.initHover();
this.initDialog();
this.bindClick();
this.show();
this.started=true;
}};
spoofProto.initHover=function(){var $=this.$;
$("ul.vMenu").hover(function(){$(this).addClass("popupMenuHoverState");
},function(){$(this).removeClass("popupMenuHoverState");
});
$("li.hMenuItem").hover(function(){$(this).children("ul.vMenu").show();
},function(){$("ul.vMenu").hide();
});
$("ul.vMenu > li").hover(function(){var $this=$(this),$subMenu=$this.children("ul.vMenu"),parentWidth=$this.parent().width(),parentPos=$this.parent().position();
$subMenu.css("top",parentPos.top+"px");
$subMenu.css("left",parentWidth+"px");
$subMenu.show();
},function(){$(this).children("ul.vMenu").hide();
});
};
spoofProto.initDialog=function(){var $=this.$;
if($.ui&&$.isFunction($.fn.dialog)){$("#spooferInfoDialog").dialog({autoOpen:false});
$("#spooferInfoMenuItem").click(function(){$("#spooferInfoDialog").dialog("open");
return false;
});
}};
spoofProto.bindClick=function(){var me=this,$=this.$;
$("#hideSpooferBarMenuItem").click(function(){me.hideSpooferBar();
});
$("#spooferMenuButton").click(function(){me.showSpooferBar();
});
};
spoofProto.show=function(){var $=this.$;
$("#spooferDiv").css("top",0);
if(typeof SpooferMenu!=="undefined"){if(SpooferMenu.visible){this.showSpooferBar(false);
}else{this.hideSpooferBar(false);
}}};
spoofProto.hideSpooferBar=function(setPref){var $=this.$;
$("#spooferDiv").hide("fast");
$("#spooferSpacerDiv").height(0).hide();
$("#spooferMenuButton").show("fast");
if(setPref){this.setPref(false);
}};
spoofProto.showSpooferBar=function(setPref){var me=this,$=this.$;
$("#spooferDiv").slideDown(200,function(){$(this).css({"overflow":"visible"});
if($.browser.msie&&$.isFunction($.fn.support)&&!$.support.boxModel){$(this).css("position","absolute");
}var spooferBarHeight=$("#spooferDiv").outerHeight();
$("#spooferSpacerDiv").height(spooferBarHeight).show();
$("#spooferMenuButton").hide();
if(setPref){me.setPref(true);
}});
};
spoofProto.setPref=function(visible){var setPrefUrl="/gp/utilities/set-arbitrary-pref.html?prefName=spooferMenuVisible&prefValue="+visible;
this.$.ajax({url:setPrefUrl,cache:false});
};
function loadSpoofer($){var spoof=new SCUI.SpooferMenu($);
}if(typeof window.P==="function"){P.when("jQuery","ready").execute(function($){loadSpoofer($);
});
}else{if(typeof window.amznJQ==="object"&&typeof window.amznJQ.available==="function"){amznJQ.onReady("jQuery",function(){loadSpoofer(window.jQuery);
});
}else{if(typeof $!=="undefined"||typeof jQuery!=="undefined"){var $=(window.$||window.jQuery);
$(function(){loadSpoofer($);
});
}else{if(typeof ueLogError!=="undefined"){ueLogError({message:"[Unable to load Seller Central spoofer bar.]"});
}}}}})();
