/*! Copyright 2013 by Amazon.com */
(function(win,undefined){if(typeof SCUI==="undefined"){win.SCUI={};
}if(typeof SCUI.Tools==="undefined"){win.SCUI.Tools={};
}})(window);
SCUI.Tools.ButtonFix=function(){this.buttonSelector="button.awesomeButton:visible";
this.spanSelector="span.button_label";
};
SCUI.Tools.ButtonFix.prototype.fix=function(context){if(jQuery.browser.msie){var buttons=(typeof context!=="undefined")?jQuery(context).find(this.buttonSelector):jQuery(this.buttonSelector);
for(var i=0,len=buttons.size();
i<len;
i++){var button=jQuery(buttons[i]);
var span=button.children(this.spanSelector).eq(0);
button.css("width",(button.width()+this.getCap(button))+"px");
span.css("width",span.width()+"px");
}}};
SCUI.Tools.ButtonFix.prototype.getCap=function(button){var cap=7;
if(button.hasClass("buttonSmall")){cap=5;
}else{if(button.hasClass("buttonTiny")){cap=3;
}}return cap;
};
function fixButtonWidths(context){var fixer=new SCUI.Tools.ButtonFix();
fixer.fix(context);
}function changeAmznButtonLabel(buttonID,newLabel){if(jQuery("#"+buttonID)){jQuery("#"+buttonID+" > span").html(newLabel);
fixButtonWidths();
}}function disableAmznButton(buttonID){var btn=jQuery("#"+buttonID);
var btnSpan=jQuery("#"+buttonID+" > span");
var buttonClasses=["primaryLargeButton","secondaryLargeButton","primarySmallButton","secondarySmallButton","primaryTinyButton","secondaryTinyButton"];
jQuery.each(buttonClasses,function(index,className){if(btn.hasClass(className)){btn.removeClass(className);
btn.addClass(className+"Ghost");
return false;
}});
btnSpan.addClass("button_disabled");
btn.attr("disabled","disabled");
}function enableAmznButton(buttonID){var btn=jQuery("#"+buttonID);
var btnSpan=jQuery("#"+buttonID+" > span");
var buttonClasses=["primaryLargeButton","secondaryLargeButton","primarySmallButton","secondarySmallButton","primaryTinyButton","secondaryTinyButton"];
jQuery.each(buttonClasses,function(index,className){if(btn.hasClass(className+"Ghost")){btn.removeClass(className+"Ghost");
btn.addClass(className);
return false;
}});
btnSpan.removeClass("button_disabled");
btn.removeAttr("disabled");
}(function(SCUI){SCUI.Tools.isTouchDevice=function(){return !!("ontouchstart" in window)||window.navigator.msMaxTouchPoints;
};
SCUI.Tools.logError=function(errorString){if(typeof ueLogError!=="undefined"){ueLogError({message:"["+errorString+"]"});
}};
SCUI.Tools.bigLoad=function(func){$=(window.jQuery||window.$);
if(typeof window.P==="function"){P.when("jQuery").execute(function($){func($);
});
}else{if(typeof window.amznJQ==="object"&&typeof window.amznJQ.available==="function"){amznJQ.available("jQuery",function(){func(jQuery);
});
}else{if(typeof $!=="undefined"){$(function(){func($);
});
}else{SCUI.Tools.logError("Unable to load SC Nav: missing jQuery dependency");
}}}};
})(window.SCUI);
(function(){function scResponsiveNav($){this.$=$||window.$||window.jQuery;
this.options={"isTouchDevice":SCUI.Tools.isTouchDevice(),"navRoot":"#sc-masthead","tabsRoot":"#sc-top-nav","tabMenuRoot":"#sc-top-nav-root","settingsRoot":"#sc-quicklink-settings","langSwitcherRoot":"#sc-lang-switcher-header","mobileTabsIcon":"#sc-top-nav-icon","dropdown":".sc-drop-nav","dropdownTrigger":".sc-menu-trigger","mobileIcon":"sc-mobile-icon","navOpenClass":"nav-open","navOpenMobileClass":"sc-m-nav-open","navTab":"sc-level1","navBack":"li.sc-mobile-back","subNavOpen":"sub-nav-open","quickLink":"sc-quicklink","hoverNav":"sc-hover-nav","fullBG":"#sc-nav-full-bg","snesDropdownTrigger":"#sc-snes > .sc-menu-trigger","snesID":"#sc-snes","snesContentID":"#sc-snes-content","snesNumSelector":"ul#sc-snes-list","snesNumAttr":"snes-number","snesNumID":"#sc-snes-number","snesActiveClass":"sc-snes-active","snesOpen":false,"snesOpenTimer":null,"snesOpenTimerLength":300,"snesNumber":0,"snesTypeSelector":".sc-snes-item","snesTypeAttr":"data-notificationType","menuOpenEvent":"menuOpen"};
this.initialized=false;
this.init();
}navProto=scResponsiveNav.prototype;
navProto.initJqObjects=function(){this.options.$navRoot=this.$(this.options.navRoot);
this.options.$tabMenuRoot=this.$(this.options.tabMenuRoot);
};
navProto.isAvailable=function(){return(this.options.$navRoot.size()>0);
};
navProto.init=function(){if(!SCUI.Tools.isNavInit){SCUI.Tools.isNavInit=true;
this.initJqObjects();
if(this.isAvailable()){if(!this.options.isTouchDevice){this.bindMenuHover();
}this.bindTabClick();
this.bindNavBackClick();
this.extendBg();
this.windowResize();
this.getNotifications();
this.bindMpsLangSwitcherEvents();
if(typeof SCUI.Tools.uaPopover!=="undefined"){this.setupUAPopover();
}if(SCUI.Tools.isUsingIE6){this.ie6Setup();
}this.bindCloseOnClickOutside();
this.bindSnesOpen();
this.initialized=true;
}}};
navProto.bindMpsLangSwitcherEvents=function(){var that=this,$=that.$;
if($("#sc-mls").length!==0){this.bindCombinedMpsLangSwitcherEvents();
}var changeMarketFromOldSwitcher=function(){var $this=$(this);
var iwsSelected=$this.attr("iwsSelected");
var marketplaceID=$this.attr("value");
if(iwsSelected==="1"){marketplaceChangedIWS(marketplaceID);
}else{marketplaceChanged(marketplaceID);
}};
$("#sc-mkt-switcher-select").change(changeMarketFromOldSwitcher);
};
navProto.bindCombinedMpsLangSwitcherEvents=function(){var that=this,$=that.$;
var $mls=$("#sc-mls"),$mlsText=$("#sc-mls-txt"),$mlsPopover=$("#sc-mls-popover"),$mlsMarketMenu=$("#sc-mls-popover").find(".sc-mls-marketcolumn"),$mlsLanguageList=$("#sc-mls-popover").find(".sc-mls-lang-list").find("li"),$mlsPopoverArrow=$("#sc-mls-txt").find(".sc-mls-poparrow-border"),mlsActiveMarketRow=null,mlsMouseLocs=[],mlsLastDelayLoc=null,mlsTimeoutId=null,mlsPopoverHideTimeout=null,mlsOptions={marketRowSelector:"li",columnHeaderSelector:"p",marketSubMenuSelector:"*",mlsTolerance:75,mlsActivateMarket:function(row){if(!$(row)){return;
}var $row=$(row),marketplaceRowID=$row.attr("id");
if(!marketplaceRowID){return;
}var marketplaceNo=marketplaceRowID.split("-")[3];
mlsShowLanguages(marketplaceNo,that.numberOfMarketplaces);
}};
var MLS_MOUSE_LOCS_TRACKED=3,MLS_DELAY=300;
var mlsMouseMove=function(e){mlsMouseLocs.push({x:e.pageX,y:e.pageY});
if(mlsMouseLocs.length>MLS_MOUSE_LOCS_TRACKED){mlsMouseLocs.shift();
}};
var mouseLeaveMarketRow=function(){if(mlsTimeoutId){clearTimeout(mlsTimeoutId);
}};
var mouseEnterMarketRow=function(){if(mlsTimeoutId){clearTimeout(mlsTimeoutId);
}possiblyActivateMarket(this);
};
var mouseClickMarketRow=function(){var $this=$(this);
var marketplaceElementID=$this.attr("id");
if(marketplaceElementID){hideMLSPopover();
var marketplaceID=$this.attr("marketplaceid");
mlsMarketplaceChange(that.iwsSelected,marketplaceID);
}};
var mlsMarketplaceChange=function(iwsSelected,marketplaceID){if(iwsSelected==="1"){marketplaceChangedIWS(marketplaceID);
}else{marketplaceChanged(marketplaceID);
}};
var mlsActivateMarket=function(row){if(row==mlsActiveMarketRow){return;
}mlsOptions.mlsActivateMarket(row);
mlsActiveMarketRow=row;
};
var possiblyActivateMarket=function(row){var delay=marketActivationDelay();
if(delay){mlsTimeoutId=setTimeout(function(){possiblyActivateMarket(row);
},delay);
}else{mlsActivateMarket(row);
}};
var marketActivationDelay=function(){if(!mlsActiveMarketRow||!$(mlsActiveMarketRow)||!$(mlsActiveMarketRow).is(mlsOptions.marketSubMenuSelector)){return 0;
}var offset=$mlsMarketMenu.offset(),upperLeft={x:offset.left,y:offset.top-mlsOptions.mlsTolerance},upperRight={x:offset.left+$mlsMarketMenu.outerWidth(),y:upperLeft.y},lowerLeft={x:offset.left,y:offset.top+$mlsMarketMenu.outerHeight()+mlsOptions.mlsTolerance},lowerRight={x:offset.left+$mlsMarketMenu.outerWidth(),y:lowerLeft.y},loc=mlsMouseLocs[mlsMouseLocs.length-1],prevLoc=mlsMouseLocs[0];
if(!loc){return 0;
}if(!prevLoc){prevLoc=loc;
}if(mlsLastDelayLoc&&loc.x==mlsLastDelayLoc.x&&loc.y==mlsLastDelayLoc.y){return 0;
}function slope(a,b){return(b.y-a.y)/(b.x-a.x);
}var decreasingCorner=upperRight,increasingCorner=lowerRight;
var decreasingSlope=slope(loc,decreasingCorner),increasingSlope=slope(loc,increasingCorner),prevDecreasingSlope=slope(prevLoc,decreasingCorner),prevIncreasingSlope=slope(prevLoc,increasingCorner);
if(decreasingSlope<prevDecreasingSlope&&increasingSlope>prevIncreasingSlope){mlsLastDelayLoc=loc;
return MLS_DELAY;
}mlsLastDelayLoc=null;
return 0;
};
var mouseEnterMLS=function(){if(mlsPopoverHideTimeout){clearTimeout(mlsPopoverHideTimeout);
}};
var mouseExitMLS=function(){mlsPopoverHideTimeout=setTimeout(function(){hideMLSPopover();
mlsActiveMarketRow=null;
mlsMouseLocs=[];
mlsLastDelayLoc=null;
mlsTimeoutId=null;
},MLS_DELAY);
};
var showMLSPopover=function(){$mlsPopover.css("display","inline-block");
$mlsPopoverArrow.css("display","inline-block");
var numberOfMarketplaces=$mlsText.attr("numberOfMarketplaces");
var currentMarketplaceNo=$mlsText.attr("currentMarketplaceNo");
var iwsSelected=$mlsText.attr("iwsSelected");
that.numberOfMarketplaces=numberOfMarketplaces;
that.iwsSelected=iwsSelected;
if(!numberOfMarketplaces||!currentMarketplaceNo){return;
}$("#sc-mls-market-"+numberOfMarketplaces).css("margin-bottom","15px");
mlsShowLanguages(currentMarketplaceNo,that.numberOfMarketplaces);
};
var hideMLSPopover=function(){$mlsPopover.hide();
$mlsPopoverArrow.hide();
};
var mlsShowLanguages=function(marketplaceNo,numberOfMarketplaces){if(!marketplaceNo||!numberOfMarketplaces){return;
}for(var j=1;
j<=numberOfMarketplaces;
j++){$("#sc-mls-lang-"+j).hide();
$("#sc-mls-market-"+j).attr("class","sc-mls-marketnotselected");
}var selectedmarket=$("#sc-mls-market-"+marketplaceNo);
selectedmarket.attr("class","sc-mls-marketselected");
selectedmarket.css("margin-right","-1px");
var langElement=$("#sc-mls-lang-"+marketplaceNo);
langElement.show();
var defaultSelectedLanguageCode=langElement.attr("defaultSelectedLanguageCode");
langElement.children().each(function(){var $this=$(this);
if($this.attr("language")===defaultSelectedLanguageCode){$this.attr("class","sc-mls-langselected");
}else{$this.attr("class","sc-mls-langnotselected");
}});
};
var mlsLanguageClick=function(){var $this=$(this);
var langElement=$this.parent().attr("id");
if(!langElement){return;
}var langID=langElement.split("-")[3];
if(!langID){return;
}var marketplaceElement=$("#sc-mls-market-"+langID);
if(!marketplaceElement){return;
}var marketplaceID=marketplaceElement.attr("marketplaceid");
var language=$this.attr("language");
var languageURL=$this.attr("languageURL");
if(!marketplaceID||!language||!languageURL){return;
}hideMLSPopover();
if(that.iwsSelected==="1"){languageMenuClickedIWS(marketplaceID,languageURL);
}else{var marketplaceName=marketplaceElement.text();
languageMenuClicked(marketplaceID,marketplaceName,languageURL);
}};
var mlsLanguageHover=function(){var $this=$(this);
$this.attr("class","sc-mls-langselected");
$this.siblings().attr("class","sc-mls-langnotselected");
};
$mlsMarketMenu.find(mlsOptions.marketRowSelector).hover(mouseEnterMarketRow,mouseLeaveMarketRow).click(mouseClickMarketRow);
$mlsPopover.find(".sc-mls-marketcolumn, .sc-mls-langcolumn").find(mlsOptions.columnHeaderSelector).hover(mouseEnterMarketRow,mouseLeaveMarketRow);
$mls.hover(mouseEnterMLS,mouseExitMLS).mousemove(mlsMouseMove);
$mlsText.mouseover(showMLSPopover);
$mlsLanguageList.mouseover(mlsLanguageHover).click(mlsLanguageClick);
};
SCUI.mlsLanguageChanged=function(marketplaceID,languageURL){showPleaseWait();
var currentMarketplaceNo=$("#sc-mls-txt").attr("currentMarketplaceNo");
if(!currentMarketplaceNo||!marketplaceID){return;
}var currentMarketplaceID=$("#sc-mls-market-"+currentMarketplaceNo).attr("marketplaceID");
if(!currentMarketplaceID){return;
}if(currentMarketplaceID===marketplaceID){changeOnlyLanguage(languageURL);
}else{changeBothMarketplaceAndLanguage(marketplaceID,languageURL);
}};
navProto.setupUAPopover=function(){var that=this,$=that.$;
this.options.hasUAPopover=true;
$(".sc-uapop-hasread").each(function(){$(this).change(function(){$this=$(this);
if($this.is(":checked")&&$this.is(":visible")){$(".sc-uapop-buttons").each(function(){$(this).show();
});
}else{$(".sc-uapop-buttons").each(function(){$(this).hide();
});
}});
});
$(".sc-uapop-remind").each(function(){$(this).click(function(){switchMarketplace(that.newMarket,that.languageURL);
});
});
$(".sc-uapop-noshow").each(function(){$(this).click(function(){$.ajax({type:"POST",url:"/gp/utilities/set-arbitrary-pref.html",data:"prefName=showUAMessage&prefValue=false",complete:switchMarketplace(that.newMarket,that.languageURL)});
});
});
$(".sc-uapop a.sc-uapop-help").click(function(){var marketDefined=typeof SCUI.Tools.uaPopover.mktInfo!=="undefined"&&typeof SCUI.Tools.uaPopover.mktInfo[that.newMarket]!=="undefined",triggerHelp=typeof SCUI.Tools.uaPopover.helpUrls!=="undefined",hasLanguage=marketDefined&&typeof SCUI.Tools.uaPopover.mktInfo[that.newMarket].language!=="undefined";
if(triggerHelp){var $this=$(this),elementID=$this.attr("urlRoot"),helpUrlRoot=SCUI.Tools.uaPopover.helpUrls[elementID],language=hasLanguage?SCUI.Tools.uaPopover.mktInfo[that.newMarket].language:"",helpUrl=helpUrlRoot+language;
openNonModalDialog(helpUrl,550,550,"scrollbars=yes",null,"yes");
}return false;
});
SCUI.Tools.uaPopover.displayPopover=function(newMarket,newMarketName,languageURL){var marketDefined=typeof SCUI.Tools.uaPopover.mktInfo!=="undefined"&&typeof SCUI.Tools.uaPopover.mktInfo[newMarket]!=="undefined",showFlag=marketDefined&&typeof SCUI.Tools.uaPopover.mktInfo[newMarket].flagURL!=="undefined",isRetailMkt=SCUI.Tools.uaPopover.retailMkt[newMarket];
that.newMarket=newMarket;
that.languageURL=languageURL;
if(!isRetailMkt){switchMarketplace(that.newMarket,that.languageURL);
return;
}SCUI.Tools.uaPopoverShowing=true;
if(showFlag){$(".sc-uapop-flag").each(function(){$(this).html('<img src="'+SCUI.Tools.uaPopover.mktInfo[newMarket].flagURL+'" class="sc-uapop-flag-img" />');
});
}if(typeof newMarketName==="undefined"){$(".sc-mkswitch-to").each(function(){$(this).text($("#sc-mkt-switcher-select option:selected").text());
});
}else{$(".sc-mkswitch-to").each(function(){$(this).text(newMarketName);
});
}$(".sc-mkt-switcher-form").each(function(){$(this).addClass("sc-uapop-show");
if($("#sc-lang-switcher-header").length){$("#sc-lang-switcher-header").addClass("sc-uapop-show");
}});
$("#sc-nav-modal-p, #sc-nav-modal-n").show();
};
};
navProto.hasVisibleIcon=function($element){return($element.hasClass(this.options.mobileIcon)&&$element.is(":visible"));
};
navProto.isHoverNavMobileMode=function($element){var $elementWithIcon;
if($element.hasClass(this.options.navTab)){$elementWithIcon=this.$(this.options.mobileTabsIcon);
}else{if($element.hasClass(this.options.quickLink)||$element.is(this.options.snesID)){$elementWithIcon=$element.find("."+this.options.mobileIcon);
}}return $elementWithIcon?this.hasVisibleIcon($elementWithIcon):false;
};
navProto.openThisMenu=function($element,thisHasVisibleIcon){$element.addClass(this.options.navOpenClass).trigger(this.options.menuOpenEvent);
if(thisHasVisibleIcon){this.options.$navRoot.addClass(this.options.navOpenMobileClass);
}this.aMenuIsOpen=1;
if($element.attr("id")=="sc-mkt-switcher"){if($(this.options.langSwitcherRoot).length){this.openThisMenu($(this.options.langSwitcherRoot),thisHasVisibleIcon);
}}};
navProto.openMobileTab=function($element,thisHasVisibleIcon){if(thisHasVisibleIcon){this.openThisMenu(this.$(this.options.tabsRoot),thisHasVisibleIcon);
}this.options.$tabMenuRoot.addClass(this.options.subNavOpen);
this.openThisMenu($element,thisHasVisibleIcon);
this.aMenuIsOpen=1;
};
navProto.closeThisMenu=function($element){$element.removeClass(this.options.navOpenClass);
if(this.options.$navRoot.hasClass(this.options.navOpenMobileClass)){this.options.$navRoot.removeClass(this.options.navOpenMobileClass);
}this.aMenuIsOpen=0;
};
navProto.closeAllMenus=function(){if((this.aMenuIsOpen||this.options.snesOpen)&&!SCUI.Tools.uaPopoverShowing){this.options.$navRoot.find(this.options.dropdown).removeClass(this.options.navOpenClass);
this.options.$tabMenuRoot.removeClass(this.options.subNavOpen);
this.options.$navRoot.removeClass(this.options.navOpenMobileClass);
this.aMenuIsOpen=0;
this.options.snesOpen=false;
}};
navProto.bindMenuHover=function(){var that=this,$=this.$;
this.options.$navRoot.find("."+this.options.hoverNav).hover(function(e){var $this=$(this);
if(that.isHoverNavMobileMode($this)){return false;
}if(that.options.snesOpen){if(that.options.snesOpenTimer){that.clearNotificationsTimer();
}that.setNotificationsTimer($this);
}else{that.closeAllMenus();
that.openThisMenu($this);
}},function(){var $this=$(this);
if(that.isHoverNavMobileMode($this)){return false;
}that.closeThisMenu($(this));
that.clearNotificationsTimer();
});
};
navProto.bindTabClick=function(){var that=this;
this.options.$navRoot.find(this.options.dropdownTrigger).click(function(e){e.stopPropagation();
var $this=that.$(this),$thisMenuRoot=$this.parent(),thisHasVisibleIcon=that.hasVisibleIcon($this),isMobileHoverNav=!thisHasVisibleIcon&&that.isHoverNavMobileMode($thisMenuRoot),isNotifications=$thisMenuRoot.is(that.options.snesID);
if(that.options.isTouchDevice||thisHasVisibleIcon||isMobileHoverNav){var isSubMenuOpen=$thisMenuRoot.hasClass(that.options.navOpenClass);
if($thisMenuRoot.is(that.options.settingsRoot)||$thisMenuRoot.hasClass(that.options.navTab)||isNotifications){e.preventDefault();
}that.closeAllMenus();
if(!isSubMenuOpen){if($thisMenuRoot.hasClass(that.options.navTab)){that.openMobileTab($thisMenuRoot,isMobileHoverNav);
}else{that.openThisMenu($thisMenuRoot,thisHasVisibleIcon);
}}}});
};
navProto.bindNavBackClick=function(){var that=this,$=this.$;
$(that.options.navBack).click(function(e){e.stopPropagation();
if(that.hasVisibleIcon($(that.options.mobileTabsIcon))){that.options.$navRoot.find("."+that.options.navTab).removeClass(that.options.navOpenClass);
that.options.$tabMenuRoot.removeClass(that.options.subNavOpen);
}});
};
navProto.bindCloseOnClickOutside=function(){var that=this,$=this.$;
$("html").click(function(){that.closeAllMenus();
});
$(that.options.tabsRoot).click(function(e){e.stopPropagation();
});
$(that.options.settingsRoot).click(function(e){e.stopPropagation();
});
$("#sc-quick-search-switch").click(function(e){e.stopPropagation();
});
if(that.options.hasUAPopover){$("#sc-nav-modal-p, #sc-nav-modal-n").click(function(e){e.stopPropagation();
});
}};
navProto.extendBg=function(){var $=this.$;
var $bgElement=$(this.options.fullBG);
$bgElement.width(0);
var windowWidth=this.$(window).width();
var docWidth=$(document).width();
if(windowWidth<docWidth){$bgElement.width(docWidth-20);
}else{$bgElement.width(0);
}};
navProto.windowResize=function(){var that=this,$=this.$;
$(window).resize(function(){that.extendBg();
});
};
navProto.getNotifications=function(){var that=this;
var $=this.$;
var data={nocache:that.getCacheBuster(),context:"nav"};
$.ajax({url:"/gp/notifications/notification-widget-internals.html",data:data,success:function(data){var $response=$(data);
that.options.snesNumber=parseInt($response.filter(that.options.snesNumSelector).attr(that.options.snesNumAttr));
if(that.options.snesNumber>0){that.updateNotificationsNum();
that.addCountMetric("snesWidgetLoad",that.options.snesNumber);
$response.children(that.options.snesTypeSelector).each(function(){var snesType=$(this).attr(that.options.snesTypeAttr);
if(typeof snesType!=="undefined"){var metricName="snesWidgetLoad:"+snesType;
that.addCountMetric(metricName,1);
}});
}$(that.options.snesContentID).prepend(data).click(function(e){e.stopPropagation();
that.notificationsContentClick($(e.target));
});
if(!that.options.isTouchDevice){that.initNotificationsTimer();
}if(SCUI.Tools.isUsingIE6){that.setupIframeShims($("#sc-snes"));
}}});
};
navProto.initHelpPopover=function(data){var $=this.$,scResponsiveNav=this,$helpLink=$("#sc-quicklink-help"),url=SCUI.Tools.AssistiveTech.uri,reqParams=SCUI.Tools.AssistiveTech.reqParams,atData;
if($helpLink.length>0){atData=$.extend(data,{url:url,reqParams:reqParams});
$.ajax({url:"/hz/recommended-help/api/get-aggregate",data:atData,dataType:"json",success:function(response){if(response&&Object.prototype.toString.call(response)==="[object Array]"){var count=0;
for(var i=0,n=response.length;
i<n;
i++){if(response[i].count){count+=response[i].count;
}}if(SCUI.Tools.PopoverCarousel&&count>0){var $popover=new SCUI.Tools.PopoverCarousel({menu:scResponsiveNav,strings:SCUI.Tools.AssistiveTech.strings,count:count});
$popover.addContents(response);
}}}});
}};
navProto.notificationsContentClick=function($target){if($target.hasClass("sc-snes-dismiss")){this.dismissNotification($target.parent("li"));
}else{if($target.is("a")){var snesType=$target.parent().attr(this.options.snesTypeAttr);
if(typeof snesType!=="undefined"){var metricName="snesWidgetClick:"+snesType;
this.addCountMetric(metricName,1);
}this.closeAllMenus();
}}};
navProto.dismissNotification=function($notification){var that=this,$=this.$;
$.ajax({url:"/gp/notifications/jshandler/notification-widget-dismiss.html",data:{nocache:that.getCacheBuster(),notificationId:$notification.attr("data-notificationId")},success:function(){$notification.slideUp("fast",function(){that.options.snesNumber--;
$notification.remove();
that.updateNotificationsNum();
});
var snesType=$notification.attr(that.options.snesTypeAttr);
if(typeof snesType!=="undefined"){var metricName="snesWidgetDismiss:"+snesType;
that.addCountMetric(metricName,1);
}}});
};
navProto.updateNotificationsNum=function(){var $=this.$;
if(this.options.snesNumber>0){$(this.options.snesNumID).html(this.options.snesNumber);
$(this.options.snesID).addClass(this.options.snesActiveClass);
}else{if(this.options.snesNumber===0){$(this.options.snesNumID).html("");
$(this.options.snesID).removeClass(this.options.snesActiveClass);
$("#sc-snes-list li:first").removeClass("sc-snes-none");
}}};
navProto.initNotificationsTimer=function(){var that=this,$=this.$;
$(that.options.snesID).mouseover(function(){that.clearNotificationsTimer();
});
$(this.options.snesID).mouseout(function(){if($(this).hasClass("nav-open")){that.options.snesOpen=true;
}else{that.options.snesOpen=false;
}});
};
navProto.setNotificationsTimer=function($element){var that=this;
that.options.snesOpenTimer=setTimeout(function(){that.closeAllMenus();
that.openThisMenu($element);
},that.options.snesOpenTimerLength);
};
navProto.clearNotificationsTimer=function(){clearTimeout(this.options.snesOpenTimer);
this.options.snesOpenTimer=null;
};
navProto.bindSnesOpen=function(){var that=this;
$(this.options.navRoot).delegate(this.options.snesID,this.options.menuOpenEvent,function(){$(that.options.snesContentID).find(that.options.snesTypeSelector).each(function(){var snesType=$(this).attr(that.options.snesTypeAttr);
if(typeof snesType!=="undefined"){var metricName="snesWidgetShow:"+snesType;
that.addCountMetric(metricName,1);
}});
});
};
navProto.setupIframeShims=function($element){var $dropDown=$element.find(".sc-sub-nav"),$iframe=$element.find(".sc-nav-iframeShim"),cssCorrection=2;
$element.addClass("sc-nav-iframeSetup");
var dropDownWidth=$dropDown.width(),dropDownHeight=$dropDown.height();
$iframe.width(dropDownWidth+cssCorrection).height(dropDownHeight+cssCorrection);
$element.removeClass("sc-nav-iframeSetup");
};
navProto.ie6Setup=function(){var that=this;
$(this.options.navRoot+" ."+this.options.hoverNav).each(function(){that.setupIframeShims($(this));
});
};
navProto.getCacheBuster=function(){return Math.random()*10000000000000000;
};
navProto.addCountMetric=function(metricName,incrementValue){if(typeof ue!=="undefined"&&typeof ue.count!=="undefined"){ue.count(metricName,(ue.count(metricName)||0)+incrementValue);
}};
SCUI.Tools.bigLoad(function($){new scResponsiveNav();
});
})();
(function(SCUI,window){var initialize=function($,window,undefined){var classes={links:"pc-links","content-container":"pc-cc",content:"pc-content",staticContent:"pc-static",tab:"pc-tab",count:"pc-tab-count","aggregate-count":"aggregate-count",selectedTab:"pc-selected",next:"pc-next","next-link":"pc-next a",previous:"pc-prev","previous-link":"pc-prev a",progress:"pc-progress",disabled:"pc-disabled",footer:"pc-footer"};
var templates={counter:'<span id="pc-count-narrow" class="aggregate-count">{{count}}</span>',skin:'<div id="popover-carousel" class="sc-sub-nav {{language}} {{quirks}}">                         <ul class="pc-links"></ul>                         <div class="pc-cc"></div>                         <div class="pc-static"></div>                     </div>',tab:'<li class="pc-tab">                     <a class="pc-links-a" href="#"><span style="display:none;" class="pc-tab-count {{type}}">{{count}}</span>{{label}}</a>                    </li>',link:'<li class="pc-link">                       <a class="pc-links-a pc-link-a" href="{{href}}">{{label}}</a>                     </li>',cover:'<div class="pc-cover">                      {{cover}}                     </div>',content:'<div class="pc-content">{{contents}}</div>                        <div class="pc-footer" style="display:none">                          <div class="pc-switcher">                            <span class="pc-prev"><a class="pc-switcher-link" href="#">{{previous}}</a></span> |                            <span class="pc-next"><a class="pc-switcher-link" href="#">{{next}}</a></span>                          </div>                          <div class="pc-progress">{{progress}}</div>                        </div>',loading:'<div class="scui-nav-loader">                          <img src="{{loader}}">                        </div>',failed:'<div class="scui-nav-loader">                         <p class="loader-text">{{error}}</p>                       </div>',"no-content":'<div class="scui-nav-loader">                                <div class="pc-title">{{no-content-title}}</div>                                <p class="loader-text">{{no-content-text}}</p>                            </div>'};
var defaults={language:"en-US",loader:"https://images-na.ssl-images-amazon.com/images/G/01/amazonui/loading/loading-2x._V391853216_.gif",tabSelectionDelay:200,mouseOutHideDelay:250,counterUpdateDelay:3000};
SCUI.Tools.PopoverCarousel=function(options){if(!(options.menu&&options.menu.closeThisMenu&&options.menu.openThisMenu)){throw new Error("Cannot initialize PopoverCarousel without `scResponsiveNav`");
}this.$this=$("#sc-quicklink-help");
this.options=$.extend({quirks:!$.boxModel||($.support&&!$.support.boxModel)?"quirks":""},defaults,options);
return this._initialize(this.$this,this.options);
};
SCUI.Tools.PopoverCarousel.prototype={addContent:function(params){var $this=this.$this,options=this.options,that=this;
if(params.href){var $link=$(this._format(templates.link,params));
$this.find("."+classes.links).append($link);
}else{var $tab=$(this._format(templates.tab,params));
if(params.count){$tab.find("."+classes.count).show();
}$tab.params=params;
$tab.isMouseInElement=$tab.hasClass(classes.selectedTab);
var selectTab=function(event){$tab.isMouseInElement=true;
setTimeout(function(){if($tab.isMouseInElement&&(!$tab.hasClass(classes.selectedTab)||!$tab.loaded||event.type=="click")){$this.find("."+classes.tab).removeClass(classes.selectedTab);
$tab.addClass(classes.selectedTab);
$tab.load();
}},options.tabSelectionDelay);
return false;
};
$tab.click(selectTab).mouseover(selectTab);
$tab.mouseout(function(){$tab.isMouseInElement=false;
});
$tab.load(function(){var content;
if($tab.loaded){content=$tab.content;
that._setupContent($tab,content);
}else{that._loadContent(params,$tab);
}});
$tab.next=function(){that._setupContent($tab,$tab.content,$tab.page+1);
};
$tab.previous=function(){that._setupContent($tab,$tab.content,$tab.page-1);
};
$tab.showCover=function(){that._setupContent($tab,$tab.content);
};
var isFirstTab=$this.find("."+classes.selectedTab).length===0;
if(isFirstTab){$tab.addClass(classes.selectedTab);
}if(isFirstTab||$tab.params.preload){$this.bind("mouseover.assistive-tech-"+params.type,function(){if(!$this.find(".sc-nav-arrow").is(":hidden")){$this.unbind("mouseover.assistive-tech-"+params.type);
$tab.load();
}});
}$(window).bind("read."+params.type,function(){setTimeout(function(){that._updateCounter(that,params.type);
},options.counterUpdateDelay);
});
$(window).bind("view."+params.type,function(event,index){var content=$tab.content;
that._setupContent($tab,content,index);
});
$(window).bind("close."+params.type,function(event,index){that._removeContent($tab,index);
});
$this.find("."+classes.links).append($tab);
}},addContents:function(arr){if(this._isArray(arr)){for(var i=0,n=arr.length;
i<n;
i++){if(this._isObject(arr[i])){this.addContent(arr[i]);
}}}},_initialize:function($this,options){var isInElement=false;
if(!isNaN(options.count)){if(options.count>0){$this.find(".sc-quick-txt").append(this._format(templates.counter,options));
}$this.append(this._format(templates.skin,options));
$this.find("a").append('<span class="sc-nav-arrow"></span>');
$this.addClass("sc-drop-nav");
$this.mouseover(function(){isInElement=true;
options.menu.openThisMenu($this);
});
$this.mouseout(function(){isInElement=false;
setTimeout(function(){if(!isInElement){options.menu.closeThisMenu($this);
}},options.mouseOutHideDelay);
});
$this.mousemove(function(){isInElement=true;
});
}return this;
},_loadContent:function(params,$tab){var content=[],options=this.options,that=this;
if(params.content){content=params.content,$tab.content=content;
this._setupContent($tab,content);
$tab.loaded=true;
}else{if(params.contentUrl){content.push(this._format(templates.loading,this.options));
if(!$tab.loading){var destinationUrl=$.isFunction(params.contentUrl)?params.contentUrl():params.contentUrl;
$tab.loading=true;
var data={uri:SCUI.Tools.AssistiveTech.uri,loadAmznJQ:window.amznJQ?0:1,loadCustomerTraining:window.CustomerTraining?0:1};
$.ajax({url:destinationUrl,data:data,dataType:"json",timeout:options.ajaxTimeout,success:function(data){if(data){$tab.loading=false;
if(that._isArray(data)||that._isObject(data)){$tab.content=content=data;
}else{$tab.content=content=[data];
}that._setupContent($tab,content);
$tab.loaded=true;
}},error:function(data){$tab.loading=false;
$tab.content=content=[templates.failed];
that._setupContent($tab,content);
$tab.loaded=true;
}});
}this._setupContent($tab,content);
}}},_setupContent:function($tab,content,idx){var $this=this.$this,options=this.options,$content;
if(!content||(this._isArray(content)&&content.length===0)){var contentParams={"no-content-title":options.strings["no-content-title"],"no-content-text":options.strings["no-content-text"]},params=$.extend({},$tab.params,contentParams);
$content=$(this._format(templates["no-content"],params));
}else{if(this._isObject(content)&&!$tab.loaded){this.$this.find("."+classes.staticContent).append(content.staticContent);
}if(idx!=null){$tab.idx=idx;
}else{$tab.idx=$tab.idx?$tab.idx:0;
}var index=$tab.idx,$next,$previous,isContentObject=this._isObject(content),contentLength=isContentObject?content.contents.length:content.length,contentParams={progress:options.strings.progress,next:options.strings.next,previous:options.strings.previous,error:options.strings.error,contents:isContentObject?content.contents[index]:content[index],cover:isContentObject?content.cover:null,index:index+1,length:contentLength},params=$.extend({},$tab.params,contentParams);
if(params.cover!=null){if(idx==null){$content=$(this._format(templates.cover,params));
}else{$content=$(this._format(templates.content,params));
$next=$content.find("."+classes["next-link"]),$previous=$content.find("."+classes["previous-link"]);
if(index===0){$previous.click($tab.showCover);
}else{$previous.click($tab.previous);
}if($tab.content&&(index>=(contentLength-1))){$next.click($tab.showCover);
}else{$next.click($tab.next);
}}}else{$content=$(this._format(templates.content,params));
$next=$content.find("."+classes["next-link"]),$previous=$content.find("."+classes["previous-link"]);
if(index===0){$previous.addClass(classes.disabled);
}else{$previous.click($tab.previous);
}if($tab.content&&(index>=(contentLength-1))){$next.addClass(classes.disabled);
}else{$next.click($tab.next);
}}}if($tab.hasClass(classes.selectedTab)){var $contentContainer=$this.find("."+classes["content-container"]);
$contentContainer.unbind();
$contentContainer.html($content);
$tab.page=index;
if(!$tab.loading){$this.find("."+classes.footer).show();
}$contentContainer.find("."+classes.content).find("img, a, a span").bind("click",function(){$this.trigger("mouseout");
});
}},_removeContent:function($tab,idx){var content=$tab.content;
if(this._isArray(content)&&content.length>idx){content.splice(idx,1);
}else{if(this._isObject(content)){content.contents.splice(idx,1);
}}$tab.content=content;
},_updateCounter:function(that,type){var $this=that.$this,options=that.options,$totalCountEl=$this.find("."+classes["aggregate-count"]),$typeCountEl=$this.find("."+classes.count+"."+type),curTotalCount=parseInt($totalCountEl.text()),curTypeCount=parseInt($typeCountEl.text());
if(!isNaN(curTotalCount)&&!isNaN(curTypeCount)){$.ajax({url:"/hz/recommended-help/api/get-count",data:{type:type,url:SCUI.Tools.AssistiveTech.uri},dataType:"json",timeout:options.ajaxTimeout,success:function(response){var newTotal=curTotalCount-curTypeCount+response.count;
that._removeOrUpdateCounter($totalCountEl,newTotal);
that._removeOrUpdateCounter($typeCountEl,response.count);
}});
}},_removeOrUpdateCounter:function($element,count){if(count>0){$element.text(count);
}else{$element.remove();
}},_format:function(html,dictionary){dictionary=dictionary||{};
var captureRegex=/{{([-\sa-zA-Z0-9]+)}}/g;
do{var replaced=false;
html=html.replace(captureRegex,function(match,capture){var matched=typeof dictionary[capture]!=="undefined";
if(matched){replaced=true;
return dictionary[capture];
}else{return match;
}});
}while(replaced);
return html.replace(captureRegex,"");
},_isObject:function(obj){return obj&&(($.isPlainObject&&$.isPlainObject(obj))||Object.prototype.toString.call(obj)==="[object Object]");
},_isArray:function(arr){return arr&&(($.isArray&&$.isArray(arr))||Object.prototype.toString.call(arr)==="[object Array]");
}};
};
SCUI.Tools.bigLoad(function($){initialize($,window);
});
})(window.SCUI,window);
var openNonModalDialog=function(url,w,h,scrollbarTag,nameStr,toolbar){if(toolbar==null){toolbar="no";
}var l=(screen.width-w)/2;
var t=(screen.height-h)/2;
window.open(url,nameStr,"height="+h+",width="+w+",left="+l+",top="+t+",status=no,toolbar="+toolbar+",menubar=no,location=no,resizable=yes,"+scrollbarTag);
};
var openModalDialog=openNonModalDialog;
var helppopup=function(url,toolbar){if(toolbar==null){toolbar="no";
}var w=725;
var h=550;
var l=(screen.width-w)/2;
var t=(screen.height-h)/2;
window.open(url,null,"height="+h+",width="+w+",left="+l+",top="+t+",status=no,toolbar="+toolbar+",menubar=no,location=no,resizable=yes,scrollbars=yes");
};
function PopupWindow_getXYPosition(anchorname){var coordinates;
if(this.type=="WINDOW"){coordinates=getAnchorWindowPosition(anchorname);
}else{coordinates=getAnchorPosition(anchorname);
}this.x=coordinates.x;
this.y=coordinates.y;
}function PopupWindow_setSize(width,height){this.width=width;
this.height=height;
}function PopupWindow_populate(contents){this.contents=contents;
this.populated=false;
}function PopupWindow_setUrl(url){this.url=url;
}function PopupWindow_setWindowProperties(props){this.windowProperties=props;
}function PopupWindow_refresh(){if(this.divName!=null){if(this.use_gebi){document.getElementById(this.divName).innerHTML=this.contents;
}else{if(this.use_css){document.all[this.divName].innerHTML=this.contents;
}else{if(this.use_layers){var d=document.layers[this.divName];
d.document.open();
d.document.writeln(this.contents);
d.document.close();
}}}}else{if(this.popupWindow!=null&&!this.popupWindow.closed){if(this.url!=""){this.popupWindow.location.href=this.url;
}else{this.popupWindow.document.open();
this.popupWindow.document.writeln(this.contents);
this.popupWindow.document.close();
}this.popupWindow.focus();
}}}function PopupWindow_showPopup(anchorname){this.getXYPosition(anchorname);
this.x+=this.offsetX;
this.y+=this.offsetY;
if(!this.populated&&(this.contents!="")){this.populated=true;
this.refresh();
}if(this.divName!=null){var theDiv=null;
var theDivShim=null;
if(this.use_gebi){theDiv=document.getElementById(this.divName);
theDivShim=document.getElementById(this.divName+"Shim");
}else{if(this.use_css){theDiv=document.all[this.divName];
theDivShim=document.all[this.divName+"Shim"];
}else{if(this.use_layers){theDiv=document.layers[this.divName];
theDivShim=document.layers[this.divName+"Shim"];
}}}if(theDiv!=null){theDiv.style.left=this.x+"px";
theDiv.style.top=this.y+"px";
theDiv.style.visibility="visible";
}if(theDivShim!=null){var divs=theDiv.getElementsByTagName("DIV");
if(divs[0]&&divs[0]==theDiv.childNodes[0]){theDivShim.style.width=divs[0].offsetWidth+"px";
theDivShim.style.height=divs[0].offsetHeight+"px";
}else{theDivShim.style.width=theDiv.offsetWidth+"px";
theDivShim.style.height=theDiv.offsetHeight+"px";
}theDivShim.style.top=theDiv.offsetTop+"px";
theDivShim.style.left=theDiv.offsetLeft+"px";
theDivShim.style.zIndex=theDiv.style.zIndex-1;
theDivShim.style.display="block";
}}else{if(this.popupWindow==null||this.popupWindow.closed){if(this.x<0){this.x=0;
}if(this.y<0){this.y=0;
}if(screen&&screen.availHeight){if((this.y+this.height)>screen.availHeight){this.y=screen.availHeight-this.height;
}}if(screen&&screen.availWidth){if((this.x+this.width)>screen.availWidth){this.x=screen.availWidth-this.width;
}}var avoidAboutBlank=window.opera||(document.layers&&!navigator.mimeTypes["*"])||navigator.vendor=="KDE"||(document.childNodes&&!document.all&&!navigator.taintEnabled);
this.popupWindow=window.open(avoidAboutBlank?"":"about:blank","window_"+anchorname,this.windowProperties+",width="+this.width+",height="+this.height+",screenX="+this.x+",left="+this.x+",screenY="+this.y+",top="+this.y+"");
}this.refresh();
}}function PopupWindow_hidePopup(){if(this.divName!=null){var theDiv=null;
var theDivShim=null;
if(this.use_gebi){theDiv=document.getElementById(this.divName);
theDivShim=document.getElementById(this.divName+"Shim");
}else{if(this.use_css){theDiv=document.all[this.divName];
theDivShim=document.all[this.divName+"Shim"];
}else{if(this.use_layers){theDiv=document.layers[this.divName];
theDivShim=document.layers[this.divName+"Shim"];
}}}if(theDiv!=null){theDiv.style.visibility="hidden";
}if(theDivShim!=null){theDivShim.style.display="none";
}}else{if(this.popupWindow&&!this.popupWindow.closed){this.popupWindow.close();
this.popupWindow=null;
}}}function PopupWindow_isClicked(e){if(this.divName!=null){if(this.use_layers){var clickX=e.pageX;
var clickY=e.pageY;
var t=document.layers[this.divName];
if((clickX>t.left)&&(clickX<t.left+t.clip.width)&&(clickY>t.top)&&(clickY<t.top+t.clip.height)){return true;
}else{return false;
}}else{if(document.all){var t=window.event.srcElement;
while(t.parentElement!=null){if(t.id==this.divName){return true;
}t=t.parentElement;
}return false;
}else{if(this.use_gebi&&e){var t=e.target||e.srcElement||e.originalTarget;
while(t.parentNode!=null){if(t.id==this.divName){return true;
}t=t.parentNode;
}return false;
}}}return false;
}return false;
}function PopupWindow_hideIfNotClicked(e){if(this.autoHideEnabled&&!this.isClicked(e)){this.hidePopup();
}}function PopupWindow_autoHide(){this.autoHideEnabled=true;
}function PopupWindow_hidePopupWindows(e){for(var i=0;
i<popupWindowObjects.length;
i++){if(popupWindowObjects[i]!=null){var p=popupWindowObjects[i];
p.hideIfNotClicked(e);
}}}function PopupWindow_attachListener(){if(document.layers){document.captureEvents(Event.MOUSEUP);
}window.popupWindowOldEventListener=document.onmouseup;
if(window.popupWindowOldEventListener!=null){document.onmouseup=new Function("window.popupWindowOldEventListener(); PopupWindow_hidePopupWindows();");
}else{document.onmouseup=PopupWindow_hidePopupWindows;
}}function PopupWindow(){if(!window.popupWindowIndex){window.popupWindowIndex=0;
}if(!window.popupWindowObjects){window.popupWindowObjects=new Array();
}if(!window.listenerAttached){window.listenerAttached=true;
PopupWindow_attachListener();
}this.index=popupWindowIndex++;
popupWindowObjects[this.index]=this;
this.divName=null;
this.popupWindow=null;
this.width=0;
this.height=0;
this.populated=false;
this.visible=false;
this.autoHideEnabled=false;
this.contents="";
this.url="";
this.windowProperties="toolbar=no,location=no,status=no,menubar=no,scrollbars=auto,resizable,alwaysRaised,dependent,titlebar=no";
if(arguments.length>0){this.type="DIV";
this.divName=arguments[0];
}else{this.type="WINDOW";
}this.use_gebi=false;
this.use_css=false;
this.use_layers=false;
if(document.getElementById){this.use_gebi=true;
}else{if(document.all){this.use_css=true;
}else{if(document.layers){this.use_layers=true;
}else{this.type="WINDOW";
}}}this.offsetX=0;
this.offsetY=0;
this.getXYPosition=PopupWindow_getXYPosition;
this.populate=PopupWindow_populate;
this.setUrl=PopupWindow_setUrl;
this.setWindowProperties=PopupWindow_setWindowProperties;
this.refresh=PopupWindow_refresh;
this.showPopup=PopupWindow_showPopup;
this.hidePopup=PopupWindow_hidePopup;
this.setSize=PopupWindow_setSize;
this.isClicked=PopupWindow_isClicked;
this.autoHide=PopupWindow_autoHide;
this.hideIfNotClicked=PopupWindow_hideIfNotClicked;
}window.SCUI.DapperMenu=(function($){var defaultItems={collapse:{title:"",href:"#"}};
var widgetMenuFns={triggerSelector:".widget-menu-arrow",menuSelector:".widget-menu",contentListSelector:".widget-content",iframeShimSelector:".widget-iframe-shim",menuPosnClass:{below:"below",above:"above"},hoverStateClass:"hoverState",headerClass:"widget-header",widgetContentClass:"widget-inside",overrideDefault:false,positionMenuLeft:false,paddingOffset:3,pageBottomFudge:25,slideSpeed:250,timeoutTime:400,menuItems:{},supportFns:{},callbackFns:{},displayTimer:undefined,widgetID:""};
var module={};
module.setMenuStrings=function(config){config=config?config:{};
$.each(config,function(menuItem,string){var isAltTxt=menuItem.match(/altTxt/gi);
if(!isAltTxt&&typeof defaultItems[menuItem]==="undefined"){defaultItems[menuItem]={};
}if(isAltTxt){menuItem=menuItem.replace(/_altTxt/gi,"");
defaultItems[menuItem].altTxt=string;
}else{defaultItems[menuItem].title=string;
}});
};
module.setMenu=function(config){config=config?config:{};
var menu=$.extend(true,{},widgetMenuFns,config);
$("#"+menu.widgetID).find(menu.triggerSelector).mouseenter(function(){menu.clearTimer();
var $menu=$(this).parent().find(menu.menuSelector);
if($menu.is(":empty")){menu.init($menu,function(linkClasses){menu.bindMenuActions(linkClasses);
});
}}).mouseleave(function(){menu.setCloseTimer();
}).click(function(){menu.clickActions($(this));
}).end().find(menu.menuSelector).mouseenter(function(){menu.clearTimer();
}).mouseleave(function(){menu.setCloseTimer();
});
};
widgetMenuFns.checkVisible=function($menu){if($menu.css("visibility")==="visible"){return true;
}else{return false;
}};
widgetMenuFns.init=function($menu,cb){var menuHTML="",linkClasses=[],menuItemInfo={},listString="",$widgetContent=$("#"+this.widgetID).find("."+this.widgetContentClass),that=this;
if(this.overrideDefault){menuItemInfo=$.extend(true,{},this.menuItems);
}else{menuItemInfo=$.extend(true,{},defaultItems,this.menuItems);
}$.each(menuItemInfo,function(menuItemIndex,values){if(values.altHTML){menuHTML+="<li>"+values.altHTML+"</li>";
}else{if(values.href&&(values.altTxt||values.title)){listString=(menuItemIndex==="collapse"&&!$widgetContent.is(":visible"))?values.altTxt:values.title;
menuHTML+="<li><a href='"+values.href+"' class='"+menuItemIndex+"'>"+listString+"</a></li>";
}}linkClasses.push(menuItemIndex);
});
$menu.html(menuHTML);
cb(linkClasses);
};
widgetMenuFns.bindMenuActions=function(linkClasses){var $parent=$("#"+this.widgetID);
for(var i=0,len=linkClasses.length;
i<len;
i++){var callbackFunction=this.callbackFns[linkClasses[i]]?this.callbackFns[linkClasses[i]]:"";
if(this.supportFns[linkClasses[i]]){this.supportFns[linkClasses[i]]($parent.find("a."+linkClasses[i]),linkClasses[i],this,callbackFunction);
}}};
widgetMenuFns.openMenu=function(){var $parent=$("#"+this.widgetID),$menu=$parent.find(this.menuSelector),$iframe=$parent.find(this.iframeShimSelector),that=this;
if(!this.checkVisible($menu)){$parent.addClass(this.hoverStateClass);
this.setMenuPosition($menu,function(cb){that.setIframe($menu,function(cb){$menu.css({"visibility":"visible","display":"none"}).slideDown(that.slideSpeed);
if($iframe.length){$iframe.slideDown(that.slideSpeed);
}});
});
}};
widgetMenuFns.setMenuPosition=function($menu,cb){var $parent=$("#"+this.widgetID),$trigger=$("#"+this.widgetID).find(this.triggerSelector),$iframe=$("#"+this.widgetID).find(this.iframeShimSelector),posn={top:"auto",bottom:"auto",right:"auto",left:"auto"},$window=$(window);
if($trigger.offset().top+$trigger.height()+$menu.height()+this.pageBottomFudge>=$window.height()+$window.scrollTop()){$parent.addClass(this.menuPosnClass.above);
posn.top="auto";
posn.bottom=$trigger.position().top+$trigger.height()+"px";
}else{$parent.removeClass(this.menuPosnClass.above);
posn.top=$trigger.position().top+$trigger.height()+"px";
posn.bottom="auto";
}if(this.positionMenuLeft){posn.left=$trigger.position().left+"px";
}else{posn.right=$parent.outerWidth()-($trigger.position().left+$trigger.outerWidth()+this.paddingOffset)+"px";
}$menu.css(posn);
if($iframe.length){$iframe.css(posn);
}cb(true);
};
widgetMenuFns.setIframe=function($menu,cb){var $parent=$("#"+this.widgetID),$iframe=$parent.find(this.iframeShimSelector);
if($iframe.length){$iframe.css({width:$menu.outerWidth()+"px",height:$menu.outerHeight()+"px"});
}cb(true);
};
widgetMenuFns.clearTimer=function(){clearTimeout(this.displayTimer);
};
widgetMenuFns.setCloseTimer=function(){var that=this;
this.displayTimer=setTimeout(function(){that.closeMenu();
},this.timeoutTime);
};
widgetMenuFns.closeMenu=function(){var $parent=$("#"+this.widgetID),$menu=$parent.find(this.menuSelector),$iframe=$parent.find(this.iframeShimSelector);
$menu.css({"visibility":"hidden","right":"9999px"});
if($iframe.length){$iframe.hide();
}$parent.removeClass(this.hoverStateClass).removeClass(this.menuPosnClass.above);
};
widgetMenuFns.clickActions=function($trigger){var $menu=$("#"+this.widgetID).find(this.menuSelector);
if(this.checkVisible($menu)&&!$menu.is(":animated")){this.closeMenu();
}else{this.openMenu();
}};
var doTheCall=function(callbackFunction){if(callbackFunction&&typeof callbackFunction[0]==="function"){if(typeof callbackFunction[1]==="undefined"){callbackFunction[0].call();
}else{callbackFunction[0].apply(null,callbackFunction[1]);
}}};
widgetMenuFns.supportFns.collapse=function($element,elementClass,that,callbackFunction){var $parent=$("#"+that.widgetID),$content=$parent.find(that.contentListSelector+" > li").not("."+that.headerClass),menuItemInfo=$.extend(true,{},defaultItems,this.menuItems);
$element.bind("click",function(){if($content.is(":visible")){$content.fadeOut(that.slideSpeed,function(){$element.text(menuItemInfo[elementClass].altTxt);
doTheCall(callbackFunction);
});
}else{$content.fadeIn(that.slideSpeed,function(){$element.text(menuItemInfo[elementClass].title);
doTheCall(callbackFunction);
});
}return false;
});
};
widgetMenuFns.supportFns.rateWidget=function($element,elementClass,that,callbackFunction){$element.bind("click",function(e){e.preventDefault();
if(that.rateWidgetUrl&&that.widgetID){var hmdLink=unescape(that.rateWidgetUrl),hmdURL=hmdLink+"&customAttribute1Value="+that.widgetID;
openNonModalDialog(hmdURL,350,530,"scrollbars=yes");
}});
};
return module;
})(jQuery);
(function($,SCUI){SCUI.Tools.Reftag={addToUrl:function(options){if(!options.url){throw new Error("url is required");
}var tag=this.getTag(options);
var anchorParts=(options.url).split("#");
var queryParts=anchorParts[0].split("?");
var url=queryParts[0];
if(url.charAt(url.length-1)!="/"){url+="/";
}url+="ref="+tag;
if(queryParts[1]){url+="?"+queryParts[1];
}if(anchorParts[1]){url+="#"+anchorParts[1];
}return url;
},getTag:function(options){options=$.extend({to:"xx",where:"cont",from:"xx"},options);
var featureSet=this.featureSet||"xx";
var parts=[featureSet,options.to,options.where,options.from];
if(options.treatment){parts.push(options.treatment);
}return parts.join("_");
},setFeatureSet:function(featureSet){this.featureSet=featureSet;
}};
})(jQuery,window.SCUI);
/*!
 * Amazon Seller Satisfaction Widget
 * Copyright (C) 2011 by Amazon.com
 */
(function($,doc){if(typeof window.SCUI==="undefined"){window.SCUI={};
}SCUI.Satisfaction=function(options){var defaultOptions={"widgetName":"satisfaction-widget","widgetSpan":"satisfy-span","widgetString":"Rate this page","topOffset":48+50,"fadeTime":400,"callback":function(){}};
this.options=$.extend({},defaultOptions,options);
var me=this;
this.getWidget=function(){return $("#"+this.options.widgetName);
};
this.insert=function(){var widget=doc.createElement("div"),span=doc.createElement("span");
widget.id=this.options.widgetName;
span.className=this.options.widgetSpan;
span.innerHTML=this.options.widgetString;
widget.appendChild(span);
$("body").append(widget);
};
this.display=function(){this.getWidget().css("top",this.getTopPosition()).show().bind("click",this.options.callback);
};
this.getTopPosition=function(){var top,container,merchContainer=$("#merchant-bar-container"),subnavContainer=$("#subnav_container"),topNavContainer=$("#topNavContainer"),widget=this.getWidget();
if(merchContainer.length){container=merchContainer;
}else{if(subnavContainer.length){container=subnavContainer;
}else{if(topNavContainer.length){container=topNavContainer;
}}}top=(container)?container.offset().top+container.height():200;
if(!isNaN(this.options.topOffset)){top+=this.options.topOffset;
}return top;
};
this.hide=function(){this.getWidget().fadeOut(this.options.fadeTime);
};
this.init=function(){this.insert();
this.display();
};
};
})(jQuery,document,undefined);
(function($){$.fn.scScreenCenter=function(){var $win=$(window);
this.css({"position":"absolute","top":Math.max(0,(($win.height()-this.outerHeight())/2)+$win.scrollTop())+"px","left":Math.max(0,(($win.width()-this.outerWidth())/2)+$win.scrollLeft())+"px"});
return this;
};
$.fn.scScreenFill=function(){this.css({"position":"absolute","top":0,"left":0,"width":$(window).width(),"height":$(document).height()});
return this;
};
SCUI.Tools.PleaseWait=function(options){var defaults={"mask":$("#pleasewaitmask"),"message":$("#pleasewaitmsg")};
this.options=$.extend({},defaults,options);
var mask=this.options.mask,message=this.options.message;
this.show=function(){if(mask.length&&message.length){if($.browser.msie&&$.browser.version==="6.0"){$("select").each(function(i,item){$(item).css("visibility","hidden");
});
}mask.show().scScreenFill();
message.show().scScreenCenter();
}};
this.hide=function(){if(mask.length){mask.hide();
}if(message.length){message.hide();
}};
};
})(jQuery);
function getAnchorPosition(anchorname){var useWindow=false;
var coordinates=new Object();
var x=0,y=0;
var use_gebi=false,use_css=false,use_layers=false;
if(document.getElementById){use_gebi=true;
}else{if(document.all){use_css=true;
}else{if(document.layers){use_layers=true;
}}}if(use_gebi&&document.all){x=AnchorPosition_getPageOffsetLeft(document.all[anchorname]);
y=AnchorPosition_getPageOffsetTop(document.all[anchorname]);
}else{if(use_gebi){var o=document.getElementById(anchorname);
x=AnchorPosition_getPageOffsetLeft(o);
y=AnchorPosition_getPageOffsetTop(o);
}else{if(use_css){x=AnchorPosition_getPageOffsetLeft(document.all[anchorname]);
y=AnchorPosition_getPageOffsetTop(document.all[anchorname]);
}else{if(use_layers){var found=0;
for(var i=0;
i<document.anchors.length;
i++){if(document.anchors[i].name==anchorname){found=1;
break;
}}if(found==0){coordinates.x=0;
coordinates.y=0;
return coordinates;
}x=document.anchors[i].x;
y=document.anchors[i].y;
}else{coordinates.x=0;
coordinates.y=0;
return coordinates;
}}}}coordinates.x=x;
coordinates.y=y;
return coordinates;
}function getAnchorWindowPosition(anchorname){var coordinates=getAnchorPosition(anchorname);
var x=0;
var y=0;
if(document.getElementById){if(isNaN(window.screenX)){x=coordinates.x-document.body.scrollLeft+window.screenLeft;
y=coordinates.y-document.body.scrollTop+window.screenTop;
}else{x=coordinates.x+window.screenX+(window.outerWidth-window.innerWidth)-window.pageXOffset;
y=coordinates.y+window.screenY+(window.outerHeight-24-window.innerHeight)-window.pageYOffset;
}}else{if(document.all){x=coordinates.x-document.body.scrollLeft+window.screenLeft;
y=coordinates.y-document.body.scrollTop+window.screenTop;
}else{if(document.layers){x=coordinates.x+window.screenX+(window.outerWidth-window.innerWidth)-window.pageXOffset;
y=coordinates.y+window.screenY+(window.outerHeight-24-window.innerHeight)-window.pageYOffset;
}}}coordinates.x=x;
coordinates.y=y;
return coordinates;
}function AnchorPosition_getPageOffsetLeft(el){var ol=el.offsetLeft;
while((el=el.offsetParent)!=null){ol+=el.offsetLeft;
}return ol;
}function AnchorPosition_getWindowOffsetLeft(el){return AnchorPosition_getPageOffsetLeft(el)-document.body.scrollLeft;
}function AnchorPosition_getPageOffsetTop(el){var ot=el.offsetTop;
while((el=el.offsetParent)!=null){ot+=el.offsetTop;
}return ot;
}function AnchorPosition_getWindowOffsetTop(el){return AnchorPosition_getPageOffsetTop(el)-document.body.scrollTop;
}(function($){SCUI.SidePanel=function(containerID){this.$contentContainer=$("#"+containerID);
this.settings={contentAlignment:"right"};
this.selectors={$document:$(document),$window:$(window)};
this.geometry={totalWidth:null,offset:this.$contentContainer.offset().top,marginTopMax:this.selectors.$document.height()-this.selectors.$window.height()-this.$contentContainer.offset().top};
$.browser.safari=navigator.vendor==="Apple Computer, Inc.";
this.initialize();
};
$.extend(SCUI.SidePanel.prototype,{initialize:function(){if($("#sc-sidepanel").hasClass("sc-sp-right")){this.settings.contentAlignment="left";
}this.$contentContainer.css("float",this.settings.contentAlignment);
this.resize();
this.setResizeBindings();
this.setExpanderBindings();
},resize:function(){var $this=$("#sc-sidepanel"),scrollTop=this.selectors.$window.scrollTop(),windowHeight=this.selectors.$window.height(),newMarginTop=scrollTop-this.geometry.offset,newHeight=windowHeight-this.geometry.offset+scrollTop;
if(newHeight>windowHeight){newHeight=windowHeight;
}if(newMarginTop>this.geometry.marginTopMax){newMarginTop=this.geometry.marginTopMax;
}if(newMarginTop<0){newMarginTop=0;
}if($.browser.safari){$("body").height("100%");
}$this.height(newHeight);
$this.css("margin-top",newMarginTop+"px");
$this.width($this.find(".sc-sp-cont").outerWidth()+$this.find(".sc-sp-expander").outerWidth());
this.geometry.totalWidth=$this.outerWidth();
this.geometry.offset=this.$contentContainer.offset().top;
this.geometry.marginTopMax=this.selectors.$document.height()-this.selectors.$window.height()-this.geometry.offset;
this.$contentContainer.width(this.selectors.$window.width()-this.geometry.totalWidth);
if($.browser.safari){$("body").height(this.selectors.$document.height());
}},toggleExpander:function(expander){var sidepanel=expander.parent();
if(sidepanel.hasClass("sc-sp-collapsed")){sidepanel.removeClass("sc-sp-collapsed");
sidepanel.addClass("sc-sp-expanded");
}else{sidepanel.addClass("sc-sp-collapsed");
sidepanel.removeClass("sc-sp-expanded");
}this.resize();
},isExpanded:function(){return $("#sc-sidepanel").hasClass("sc-sp-expanded");
},setResizeBindings:function(){var that=this;
if($.browser.msie){setInterval(function(){that.resize();
},50);
}else{this.selectors.$window.scroll(function(){that.resize();
if($.browser.mozilla){setTimeout(function(){that.resize();
},100);
}});
}this.selectors.$window.resize(function(){that.resize();
});
},setExpanderBindings:function(){var that=this;
$(".sc-sp-expander").click(function(){that.toggleExpander($(this));
});
}});
})(window.jQuery||window.$);
if(window.amznJQ){amznJQ.declareAvailable("rainier-core");
}(function(){window.amzn=window.amzn||{};
amzn.copilot=amzn.copilot||{};
var win=window,doc=document;
var url;
var headElement=doc.head||doc.getElementsByTagName("head")[0],copilotKey="cpidv",alreadyWaited=0,jqueryUnavailableMetricsKey="cpJQUnavailable",ajaxErrorMetricsKey="cpLoadResourceError",copilot_initialized=0,taxDocumentElement="#txdlContent",creditCardDocumentElement=".content-module";
amzn.copilot.init=function(){if(!copilot_initialized){amzn.copilot.checkCoPilotSession();
copilot_initialized=1;
}};
amzn.copilot.checkCoPilotSession=function(){if(doc.cookie.match(copilotKey)){if(typeof jQuery!=="undefined"){loadResources(jQuery);
}else{if(win.P&&win.P.when){win.P.when("jQuery").execute(function($){loadResources($);
});
}else{if(win.amznJQ&&win.amznJQ.available){win.amznJQ.available("jQuery",function(){loadResources(jQuery);
});
}else{waitForJquery();
}}}}};
var waitForJquery=function(){if(!alreadyWaited){alreadyWaited=1;
if(doc.addEventListener){doc.addEventListener("DOMContentLoaded",amzn.copilot.checkCoPilotSession,false);
}else{if(doc.attachEvent){doc.attachEvent("onreadystatechange",function(){if(doc.readyState==="complete"){amzn.copilot.checkCoPilotSession();
}});
}}}else{if(win.ue&&(typeof win.ue.count==="function")){win.ue.count(jqueryUnavailableMetricsKey,1);
}}};
var loadResources=function(jQuery){amzn.copilot.jQuery=jQuery;
var isDebug=getUrlParameter("debugJS"),isSecure=win.location.protocol==="https:"?1:0;
if(amzn.copilot.jQuery.ajax){amzn.copilot.jQuery.ajax({url:"/hz/copilot/get_copilot_resources",dataType:"json",data:{isDebug:isDebug,isSecure:isSecure},success:function(response){amzn.copilot.vip=response.serviceEndPoint;
setupCoPilotSession(response);
},error:function(){}});
}};
var setupCoPilotSession=function(copilotResources){var $=amzn.copilot.jQuery;
var successFunction=function(){amzn.copilot.setup($.extend({isContinuedSession:true},copilotResources));
};
var CSSUrls=copilotResources.CSSUrls||[copilotCSSUrl];
$.each(CSSUrls,function(index,value){injectCSS(value);
});
url=SCUI.Tools.AssistiveTech.uri;
if(url==="/gp/tax/tax-library.html"){maskElement(taxDocumentElement);
}else{if(url==="/gp/on-board/configuration/index.html"){maskElement(creditCardDocumentElement);
}}var requireSynchronousLoading=getUrlParameter("forceSynchronousJS");
var JSUrls=copilotResources.JSUrls||[copilotJSUrl];
$.each(JSUrls,function(index,value){injectJS(value,requireSynchronousLoading,successFunction);
});
},injectJS=function(url,sync,successFunction){var script=doc.createElement("script");
script.type="text/javascript";
script.src=url;
script.async=sync?false:true;
if(successFunction){script.onload=successFunction;
}headElement.appendChild(script);
},injectCSS=function(url){var style=doc.createElement("link");
style.type="text/css";
style.rel="stylesheet";
style.href=url;
headElement.appendChild(style);
};
function getUrlParameter(paramName){var searchString=win.location.search.substring(1);
var paramList=searchString.split("&");
for(var i=0;
i<paramList.length;
i++){var queryparamName=paramList[i].split("=");
if(queryparamName[0]===paramName){return queryparamName[1];
}}}function maskElement(elemId){var $=amzn.copilot.jQuery;
var element=$(elemId);
if(element.length>0){element.addClass("copilot-secure-display");
}}})();
amzn.copilot.init();
var lensParser=(function($){var numOfPendingRequestsToLens=0;
var originalTexts={};
var translationCache;
var sourceLanguage="en";
var targetLanguage="zh";
var init=function(pageId,targetLang,cacheVersion){translationCache=new lensCache.LensCache(pageId,targetLanguage,cacheVersion);
targetLanguage=targetLang;
};
var parseAndTranslate=function(domToParse,pageId,domsToSkip,batchSize,callback){var text_node_pair=getTextNodePairs(domToParse,domsToSkip);
if($.isEmptyObject(text_node_pair)){callback();
return;
}var i=0;
var texts=[];
for(var text in text_node_pair){if(i<batchSize){texts.push(text);
i++;
}else{texts.push(text);
translate(texts,sourceLanguage,targetLanguage,pageId,text_node_pair,callback);
texts=[];
i=0;
}}if(i>0){translate(texts,sourceLanguage,targetLanguage,pageId,text_node_pair,callback);
}};
var getTextNodePairs=function(node,domsToSkip){var textNodePairs={};
getTextFromInnerMostChild(node,textNodePairs,domsToSkip);
return textNodePairs;
};
var translate=function(texts,fromLanguage,toLanguage,pageId,textNodePairs,callback){var texts_to_translate=[];
for(var k=0;
k<texts.length;
k++){var key=texts[k];
var value=translationCache.getItem(key);
if(value!==null){var nodes=textNodePairs[key];
for(var i in nodes){nodes[i].textContent=value;
}if(!(value in originalTexts)){originalTexts[value]=key;
}}else{texts_to_translate.push(key);
}}addCountMetric("lens:"+toLanguage+":"+"cacheHit",texts.length-texts_to_translate.length);
addCountMetric("lens:"+toLanguage+":"+"cacheMiss",texts_to_translate.length);
if($.isEmptyObject(texts_to_translate)){callback();
return;
}var requestData=JSON.stringify({source:fromLanguage,destination:toLanguage,pageId:pageId,texts:texts_to_translate});
numOfPendingRequestsToLens++;
$.ajax({type:"POST",url:"/lens/translate",data:{requestJson:requestData},success:function(response){try{for(var k in response){var v=response[k];
originalTexts[$.trim(v)]=k;
translationCache.setItem(k,v);
var nodes=textNodePairs[k];
for(var i in nodes){nodes[i].textContent=v;
}}}catch(err){addCountMetric("lens:"+toLanguage+":"+"error",1);
console.log("error in translation request: "+err.message);
}numOfPendingRequestsToLens--;
if(numOfPendingRequestsToLens===0){callback();
}},error:function(err){addCountMetric("lens:"+toLanguage+":"+"error",1);
numOfPendingRequestsToLens--;
if(numOfPendingRequestsToLens===0){callback(err);
}}});
};
var isHtmlNode=function(node){switch(node.nodeName){case"SCRIPT":case"NOSCRIPT":case"STYLE":return false;
default:return true;
}};
var getTextFromInnerMostChild=function(node,textNodePairs,domsToSkip){if(isHtmlNode(node)===false||!node.childNodes||(node.id&&domsToSkip[node.id]===true)||(node.className&&domsToSkip[node.className]===true)){return;
}var childrenCount=node.childNodes.length;
if(childrenCount===0&&node.nodeType===3){var str=$.trim(node.textContent);
if(str&&!(str in originalTexts)){if(!(str in textNodePairs)){textNodePairs[str]=[];
}textNodePairs[str].push(node);
}}else{for(var i=0;
i<childrenCount;
i++){getTextFromInnerMostChild(node.childNodes[i],textNodePairs,domsToSkip);
}}};
var addCountMetric=function(metricName,incrementValue){if(typeof ue!=="undefined"&&typeof ue.count!=="undefined"){ue.count(metricName,incrementValue);
}};
return{init:init,parseAndTranslate:parseAndTranslate};
})(jQuery);
(function($){var CONSTANTS={DEFAULT_DOM_NODES:[{identifier:"#sc-masthead",pageId:"HEADER"},{identifier:"#sc_footer_container",pageId:"FOOTER"},{identifier:".sc-footer",pageId:"FOOTER"}],DEFAULT_DOM_NODES_TO_SKIP:{"sc-mls":true,"sc_footer_language_switcher":true},DEFAULT_DOM_NODES_TO_SKIP_FOR_BODY:{"sc-masthead":true,"sc_footer_container":true,"sc-footer":true}};
var LENS_OBJECT={name:"input[name='lensLanguageName']",whitelistAttr:"whitelisted",blacklistAttr:"blacklisted",versionAttr:"version",defaultValue:"#*"};
function LensObserver(){this.lensObserver=null;
}LensObserver.prototype.startObserving=function(domNodesToObserve,callback){try{this.lensObserver=new MutationObserver(function(mutations){callback();
});
var config={subtree:true,childList:true};
for(var i=0;
i<domNodesToObserve.length;
i++){this.lensObserver.observe(domNodesToObserve[i],config);
}}catch(err){for(var i=0;
i<domNodesToObserve.length;
i++){domNodesToObserve[i].addEventListener("DOMNodeInserted",callback);
}}};
LensObserver.prototype.stopObserving=function(domNodesToObserve,callback){if(this.lensObserver!==undefined&&this.lensObserver!==null){this.lensObserver.disconnect();
}else{for(var i=0;
i<domNodesToObserve.length;
i++){domNodesToObserve[i].removeEventListener("DOMNodeInserted",callback);
}}};
function LensLoader($){this.$=$||window.$||window.jQuery;
$=this.$;
this.BATCH_SIZE=20;
this.DomNodesToTranslate=[];
this.DomNodeNames=[];
this.DomNodesToSkip={};
this.DomNodesToSkipForBody={};
this.pageId=location.pathname.replace(/ref=.*/g,"");
this.version="1";
this.targetLanguage="zh";
}LensLoader.prototype.init=function(){var refLensObject=$(LENS_OBJECT.name);
if(!(refLensObject.length)){return;
}this.version=refLensObject.attr(LENS_OBJECT.versionAttr);
if(this.version===undefined||this.version===""){this.version="1";
}this.targetLanguage=refLensObject.attr("value").split("_")[0];
if(typeof ue!=="undefined"&&typeof ue.count!=="undefined"){ue.count("lens:"+this.targetLanguage+":"+"pageHit",1);
}var whitelisted=refLensObject.attr(LENS_OBJECT.whitelistAttr);
if(whitelisted!==undefined&&whitelisted!==""){if(whitelisted===LENS_OBJECT.defaultValue){this.DomNodesToTranslate.push(document.body);
this.DomNodeNames=CONSTANTS.DEFAULT_DOM_NODES;
this.DomNodesToSkip=CONSTANTS.DEFAULT_DOM_NODES_TO_SKIP;
this.DomNodesToSkipForBody=CONSTANTS.DEFAULT_DOM_NODES_TO_SKIP_FOR_BODY;
}else{var whitelistarray=whitelisted.split("#");
for(var i=1;
i<whitelistarray.length;
i++){if($("#"+whitelistarray[i]).length){this.DomNodesToTranslate.push($("#"+whitelistarray[i])[0]);
}}if(!this.DomNodesToTranslate.length){return;
}}var blacklisted=refLensObject.attr(LENS_OBJECT.blacklistAttr);
if(blacklisted!==undefined&&blacklisted!==""){var blacklistarray=blacklisted.split("#");
for(var i=1;
i<blacklistarray.length;
i++){this.DomNodesToSkipForBody[blacklistarray[i]]=true;
}}}this.customDomTranslate();
};
LensLoader.prototype.customDomTranslate=function(){var that=this;
$=that.$;
if(!this.DomNodesToTranslate.length){return;
}that.translationInProgress=true;
that.newNodeInserted=false;
var lensObserver=new LensObserver();
var newNodeInsertedCallback=function(err){if(err){lensObserver.stopObserving(that.DomNodesToTranslate,onNewNodeInserted);
return;
}that.translationInProgress=false;
if(that.newNodeInserted){onNewNodeInserted();
}};
var onNewNodeInserted=function(){if(that.translationInProgress){that.newNodeInserted=true;
return;
}else{that.translationInProgress=true;
that.newNodeInserted=false;
parseAndTranslate(that.DomNodesToTranslate,that.pageId,that.DomNodesToSkipForBody);
}};
lensParser.init(that.pageId,this.targetLanguage,this.version);
var parseAndTranslate=function(domsToTranslate,pageId,domsToSkip){for(var i=0;
i<domsToTranslate.length;
i++){lensParser.parseAndTranslate(domsToTranslate[i],pageId,domsToSkip,that.BATCH_SIZE,newNodeInsertedCallback);
}};
for(var i=0;
i<that.DomNodeNames.length;
i++){var domNode=that.DomNodeNames[i];
if($(domNode.identifier).length){parseAndTranslate($(domNode.identifier)[0],domNode.pageId,that.DomNodesToSkip);
}}parseAndTranslate(that.DomNodesToTranslate,that.pageId,that.DomNodesToSkipForBody);
lensObserver.startObserving(that.DomNodesToTranslate,onNewNodeInserted);
};
SCUI.Tools.bigLoad(function($){var lensLoader=new LensLoader($);
lensLoader.init();
});
})(jQuery);
var lensCache=(function($){var LensCache=function(keyPrefix,targetLanguage,cacheVersion){try{this.translationCache=localStorage;
this.lensPrefix="LENS#";
this.keyPrefix=this.lensPrefix+keyPrefix+"#"+targetLanguage+"#";
this.versionKey="VERSION#";
this.alreadyClearedCacheOnce=false;
var storedCacheVersion=this.getItem(this.versionKey);
if(storedCacheVersion!==cacheVersion){for(var key in this.translationCache){if(typeof key==="string"&&key.startsWith(this.keyPrefix)){this.translationCache.clear(key);
}}this.setItem(this.versionKey,cacheVersion);
}}catch(e){this.translationCache=null;
}};
LensCache.prototype.getItem=function(key){if(this.translationCache!==undefined&&this.translationCache!==null){return this.translationCache.getItem(this.keyPrefix+key);
}return null;
};
LensCache.prototype.setItem=function(key,value){if(this.translationCache!==undefined&&this.translationCache!==null){try{return this.translationCache.setItem(this.keyPrefix+key,value);
}catch(e){if(isQuotaExceeded(e)&&!this.alreadyClearedCacheOnce){this.alreadyClearedCacheOnce=true;
for(var key in this.translationCache){if(typeof key==="string"&&key.startsWith(this.lensPrefix)){this.translationCache.clear(key);
}}this.setItem(key,value);
}}}function isQuotaExceeded(e){var quotaExceeded=false;
if(e){if(e.code){switch(e.code){case 22:quotaExceeded=true;
break;
case 1014:if(e.name==="NS_ERROR_DOM_QUOTA_REACHED"){quotaExceeded=true;
}break;
}}else{if(e.number===-2147024882){quotaExceeded=true;
}}}return quotaExceeded;
}return null;
};
return{LensCache:LensCache};
})(jQuery);
